# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from aidbox.hl7_fhir_r4_core import \
    Address, Age, Annotation, Attachment, BackboneElement, CodeableConcept, Coding, ContactDetail, ContactPoint, \
    Contributor, Count, DataRequirement, Distance, Dosage, Duration, Element, ElementDefinition, Expression, \
    Extension, HumanName, Identifier, MarketingStatus, Meta, Money, Narrative, ParameterDefinition, Period, \
    Population, ProdCharacteristic, ProductShelfLife, Quantity, Range, Ratio, Reference, RelatedArtifact, \
    SampledData, Signature, SubstanceAmount, Timing, TriggerDefinition, UsageContext

from aidbox.hl7_fhir_r4_core.group import Group, GroupCharacteristic, GroupMember
from aidbox.hl7_fhir_r4_core.questionnaire import \
    Questionnaire, QuestionnaireItem, QuestionnaireItemAnswerOption, QuestionnaireItemEnableWhen, QuestionnaireItemInitial
from aidbox.hl7_fhir_r4_core.provenance import Provenance, ProvenanceAgent, ProvenanceEntity
from aidbox.hl7_fhir_r4_core.goal import Goal, GoalTarget
from aidbox.hl7_fhir_r4_core.appointment_response import AppointmentResponse
from aidbox.hl7_fhir_r4_core.research_study import \
    ResearchStudy, ResearchStudyArm, ResearchStudyObjective
from aidbox.hl7_fhir_r4_core.encounter import \
    Encounter, EncounterClassHistory, EncounterDiagnosis, EncounterHospitalization, EncounterLocation, EncounterParticipant, \
    EncounterStatusHistory
from aidbox.hl7_fhir_r4_core.clinical_impression import \
    ClinicalImpression, ClinicalImpressionFinding, ClinicalImpressionInvestigation
from aidbox.hl7_fhir_r4_core.diagnostic_report import DiagnosticReport, DiagnosticReportMedia
from aidbox.hl7_fhir_r4_core.organization_affiliation import OrganizationAffiliation
from aidbox.hl7_fhir_r4_core.guidance_response import GuidanceResponse
from aidbox.hl7_fhir_r4_core.biologically_derived_product import \
    BiologicallyDerivedProduct, BiologicallyDerivedProductCollection, BiologicallyDerivedProductManipulation, \
    BiologicallyDerivedProductProcessing, BiologicallyDerivedProductStorage
from aidbox.hl7_fhir_r4_core.compartment_definition import \
    CompartmentDefinition, CompartmentDefinitionResource
from aidbox.hl7_fhir_r4_core.substance import Substance, SubstanceIngredient, SubstanceInstance
from aidbox.hl7_fhir_r4_core.message_definition import \
    MessageDefinition, MessageDefinitionAllowedResponse, MessageDefinitionFocus
from aidbox.hl7_fhir_r4_core.slot import Slot
from aidbox.hl7_fhir_r4_core.structure_map import \
    StructureMap, StructureMapGroup, StructureMapGroupInput, StructureMapGroupRule, StructureMapGroupRuleDependent, \
    StructureMapGroupRuleSource, StructureMapGroupRuleTarget, StructureMapGroupRuleTargetParameter, StructureMapStructure
from aidbox.hl7_fhir_r4_core.substance_reference_information import \
    SubstanceReferenceInformation, SubstanceReferenceInformationClassification, SubstanceReferenceInformationGene, \
    SubstanceReferenceInformationGeneElement, SubstanceReferenceInformationTarget
from aidbox.hl7_fhir_r4_core.device_metric import DeviceMetric, DeviceMetricCalibration
from aidbox.hl7_fhir_r4_core.basic import Basic
from aidbox.hl7_fhir_r4_core.substance_source_material import \
    SubstanceSourceMaterial, SubstanceSourceMaterialFractionDescription, SubstanceSourceMaterialOrganism, \
    SubstanceSourceMaterialOrganismAuthor, SubstanceSourceMaterialOrganismHybrid, SubstanceSourceMaterialOrganismOrganismGeneral, \
    SubstanceSourceMaterialPartDescription
from aidbox.hl7_fhir_r4_core.domain_resource import DomainResource
from aidbox.hl7_fhir_r4_core.resource_families import DomainResourceFamily
from aidbox.hl7_fhir_r4_core.endpoint import Endpoint
from aidbox.hl7_fhir_r4_core.research_subject import ResearchSubject
from aidbox.hl7_fhir_r4_core.related_person import RelatedPerson, RelatedPersonCommunication
from aidbox.hl7_fhir_r4_core.effect_evidence_synthesis import \
    EffectEvidenceSynthesis, EffectEvidenceSynthesisCertainty, EffectEvidenceSynthesisCertaintyCertaintySubcomponent, \
    EffectEvidenceSynthesisEffectEstimate, EffectEvidenceSynthesisEffectEstimatePrecisionEstimate, EffectEvidenceSynthesisResultsByExposure, \
    EffectEvidenceSynthesisSampleSize
from aidbox.hl7_fhir_r4_core.imaging_study import \
    ImagingStudy, ImagingStudySeries, ImagingStudySeriesInstance, ImagingStudySeriesPerformer
from aidbox.hl7_fhir_r4_core.practitioner import Practitioner, PractitionerQualification
from aidbox.hl7_fhir_r4_core.graph_definition import \
    GraphDefinition, GraphDefinitionLink, GraphDefinitionLinkTarget, GraphDefinitionLinkTargetCompartment
from aidbox.hl7_fhir_r4_core.communication_request import \
    CommunicationRequest, CommunicationRequestPayload
from aidbox.hl7_fhir_r4_core.list import List, ListEntry
from aidbox.hl7_fhir_r4_core.flag import Flag
from aidbox.hl7_fhir_r4_core.contract import \
    Contract, ContractContentDefinition, ContractFriendly, ContractLegal, ContractRule, ContractSigner, ContractTerm, \
    ContractTermAction, ContractTermActionSubject, ContractTermAsset, ContractTermAssetContext, ContractTermAssetValuedItem, \
    ContractTermOffer, ContractTermOfferAnswer, ContractTermOfferParty, ContractTermSecurityLabel
from aidbox.hl7_fhir_r4_core.communication import Communication, CommunicationPayload
from aidbox.hl7_fhir_r4_core.media import Media
from aidbox.hl7_fhir_r4_core.device_definition import \
    DeviceDefinition, DeviceDefinitionCapability, DeviceDefinitionDeviceName, DeviceDefinitionMaterial, DeviceDefinitionProperty, \
    DeviceDefinitionSpecialization, DeviceDefinitionUdiDeviceIdentifier
from aidbox.hl7_fhir_r4_core.plan_definition import \
    PlanDefinition, PlanDefinitionAction, PlanDefinitionActionCondition, PlanDefinitionActionDynamicValue, \
    PlanDefinitionActionParticipant, PlanDefinitionActionRelatedAction, PlanDefinitionGoal, PlanDefinitionGoalTarget
from aidbox.hl7_fhir_r4_core.location import Location, LocationHoursOfOperation, LocationPosition
from aidbox.hl7_fhir_r4_core.immunization_recommendation import \
    ImmunizationRecommendation, ImmunizationRecommendationRecommendation, ImmunizationRecommendationRecommendationDateCriterion
from aidbox.hl7_fhir_r4_core.specimen_definition import \
    SpecimenDefinition, SpecimenDefinitionTypeTested, SpecimenDefinitionTypeTestedContainer, SpecimenDefinitionTypeTestedContainerAdditive, \
    SpecimenDefinitionTypeTestedHandling
from aidbox.hl7_fhir_r4_core.charge_item import ChargeItem, ChargeItemPerformer
from aidbox.hl7_fhir_r4_core.parameters import Parameters, ParametersParameter
from aidbox.hl7_fhir_r4_core.medication_knowledge import \
    MedicationKnowledge, MedicationKnowledgeAdministrationGuidelines, MedicationKnowledgeAdministrationGuidelinesDosage, \
    MedicationKnowledgeAdministrationGuidelinesPatientCharacteristics, MedicationKnowledgeCost, MedicationKnowledgeDrugCharacteristic, \
    MedicationKnowledgeIngredient, MedicationKnowledgeKinetics, MedicationKnowledgeMedicineClassification, \
    MedicationKnowledgeMonitoringProgram, MedicationKnowledgeMonograph, MedicationKnowledgePackaging, MedicationKnowledgeRegulatory, \
    MedicationKnowledgeRegulatoryMaxDispense, MedicationKnowledgeRegulatorySchedule, MedicationKnowledgeRegulatorySubstitution, \
    MedicationKnowledgeRelatedMedicationKnowledge
from aidbox.hl7_fhir_r4_core.implementation_guide import \
    ImplementationGuide, ImplementationGuideDefinition, ImplementationGuideDefinitionGrouping, ImplementationGuideDefinitionPage, \
    ImplementationGuideDefinitionParameter, ImplementationGuideDefinitionResource, ImplementationGuideDefinitionTemplate, \
    ImplementationGuideDependsOn, ImplementationGuideGlobal, ImplementationGuideManifest, ImplementationGuideManifestPage, \
    ImplementationGuideManifestResource
from aidbox.hl7_fhir_r4_core.operation_definition import \
    OperationDefinition, OperationDefinitionOverload, OperationDefinitionParameter, OperationDefinitionParameterBinding, \
    OperationDefinitionParameterReferencedFrom
from aidbox.hl7_fhir_r4_core.catalog_entry import CatalogEntry, CatalogEntryRelatedEntry
from aidbox.hl7_fhir_r4_core.bundle import \
    Bundle, BundleEntry, BundleEntryRequest, BundleEntryResponse, BundleEntrySearch, BundleLink
from aidbox.hl7_fhir_r4_core.episode_of_care import \
    EpisodeOfCare, EpisodeOfCareDiagnosis, EpisodeOfCareStatusHistory
from aidbox.hl7_fhir_r4_core.explanation_of_benefit import \
    ExplanationOfBenefit, ExplanationOfBenefitAccident, ExplanationOfBenefitAddItem, ExplanationOfBenefitAddItemDetail, \
    ExplanationOfBenefitAddItemDetailSubDetail, ExplanationOfBenefitBenefitBalance, ExplanationOfBenefitBenefitBalanceFinancial, \
    ExplanationOfBenefitCareTeam, ExplanationOfBenefitDiagnosis, ExplanationOfBenefitInsurance, ExplanationOfBenefitItem, \
    ExplanationOfBenefitItemAdjudication, ExplanationOfBenefitItemDetail, ExplanationOfBenefitItemDetailSubDetail, \
    ExplanationOfBenefitPayee, ExplanationOfBenefitPayment, ExplanationOfBenefitProcedure, ExplanationOfBenefitProcessNote, \
    ExplanationOfBenefitRelated, ExplanationOfBenefitSupportingInfo, ExplanationOfBenefitTotal
from aidbox.hl7_fhir_r4_core.procedure import Procedure, ProcedureFocalDevice, ProcedurePerformer
from aidbox.hl7_fhir_r4_core.substance_specification import \
    SubstanceSpecification, SubstanceSpecificationCode, SubstanceSpecificationMoiety, SubstanceSpecificationName, \
    SubstanceSpecificationNameOfficial, SubstanceSpecificationProperty, SubstanceSpecificationRelationship, \
    SubstanceSpecificationStructure, SubstanceSpecificationStructureIsotope, SubstanceSpecificationStructureIsotopeMolecularWeight, \
    SubstanceSpecificationStructureRepresentation
from aidbox.hl7_fhir_r4_core.concept_map import \
    ConceptMap, ConceptMapGroup, ConceptMapGroupElement, ConceptMapGroupElementTarget, ConceptMapGroupElementTargetDependsOn, \
    ConceptMapGroupUnmapped
from aidbox.hl7_fhir_r4_core.operation_outcome import OperationOutcome, OperationOutcomeIssue
from aidbox.hl7_fhir_r4_core.medicinal_product_undesirable_effect import MedicinalProductUndesirableEffect
from aidbox.hl7_fhir_r4_core.enrollment_response import EnrollmentResponse
from aidbox.hl7_fhir_r4_core.device_request import DeviceRequest, DeviceRequestParameter
from aidbox.hl7_fhir_r4_core.coverage_eligibility_response import \
    CoverageEligibilityResponse, CoverageEligibilityResponseError, CoverageEligibilityResponseInsurance, CoverageEligibilityResponseInsuranceItem, \
    CoverageEligibilityResponseInsuranceItemBenefit
from aidbox.hl7_fhir_r4_core.subscription import Subscription, SubscriptionChannel
from aidbox.hl7_fhir_r4_core.composition import \
    Composition, CompositionAttester, CompositionEvent, CompositionRelatesTo, CompositionSection
from aidbox.hl7_fhir_r4_core.person import Person, PersonLink
from aidbox.hl7_fhir_r4_core.schedule import Schedule
from aidbox.hl7_fhir_r4_core.example_scenario import \
    ExampleScenario, ExampleScenarioActor, ExampleScenarioInstance, ExampleScenarioInstanceContainedInstance, \
    ExampleScenarioInstanceVersion, ExampleScenarioProcess, ExampleScenarioProcessStep, ExampleScenarioProcessStepAlternative, \
    ExampleScenarioProcessStepOperation
from aidbox.hl7_fhir_r4_core.detected_issue import \
    DetectedIssue, DetectedIssueEvidence, DetectedIssueMitigation
from aidbox.hl7_fhir_r4_core.payment_reconciliation import \
    PaymentReconciliation, PaymentReconciliationDetail, PaymentReconciliationProcessNote
from aidbox.hl7_fhir_r4_core.risk_assessment import RiskAssessment, RiskAssessmentPrediction
from aidbox.hl7_fhir_r4_core.molecular_sequence import \
    MolecularSequence, MolecularSequenceQuality, MolecularSequenceQualityRoc, MolecularSequenceReferenceSeq, \
    MolecularSequenceRepository, MolecularSequenceStructureVariant, MolecularSequenceStructureVariantInner, \
    MolecularSequenceStructureVariantOuter, MolecularSequenceVariant
from aidbox.hl7_fhir_r4_core.measure import \
    Measure, MeasureGroup, MeasureGroupPopulation, MeasureGroupStratifier, MeasureGroupStratifierComponent, \
    MeasureSupplementalData
from aidbox.hl7_fhir_r4_core.test_report import \
    TestReport, TestReportParticipant, TestReportSetup, TestReportSetupAction, TestReportSetupActionAssert, \
    TestReportSetupActionOperation, TestReportTeardown, TestReportTeardownAction, TestReportTest, TestReportTestAction
from aidbox.hl7_fhir_r4_core.observation import \
    Observation, ObservationComponent, ObservationReferenceRange
from aidbox.hl7_fhir_r4_core.medicinal_product_manufactured import MedicinalProductManufactured
from aidbox.hl7_fhir_r4_core.coverage import \
    Coverage, CoverageClass, CoverageCostToBeneficiary, CoverageCostToBeneficiaryException
from aidbox.hl7_fhir_r4_core.message_header import \
    MessageHeader, MessageHeaderDestination, MessageHeaderResponse, MessageHeaderSource
from aidbox.hl7_fhir_r4_core.resource import Resource
from aidbox.hl7_fhir_r4_core.resource_families import ResourceFamily
from aidbox.hl7_fhir_r4_core.nutrition_order import \
    NutritionOrder, NutritionOrderEnteralFormula, NutritionOrderEnteralFormulaAdministration, NutritionOrderOralDiet, \
    NutritionOrderOralDietNutrient, NutritionOrderOralDietTexture, NutritionOrderSupplement
from aidbox.hl7_fhir_r4_core.document_manifest import DocumentManifest, DocumentManifestRelated
from aidbox.hl7_fhir_r4_core.medicinal_product_authorization import \
    MedicinalProductAuthorization, MedicinalProductAuthorizationJurisdictionalAuthorization, MedicinalProductAuthorizationProcedure
from aidbox.hl7_fhir_r4_core.research_definition import ResearchDefinition
from aidbox.hl7_fhir_r4_core.device import \
    Device, DeviceDeviceName, DeviceProperty, DeviceSpecialization, DeviceUdiCarrier, DeviceVersion
from aidbox.hl7_fhir_r4_core.family_member_history import \
    FamilyMemberHistory, FamilyMemberHistoryCondition
from aidbox.hl7_fhir_r4_core.care_team import CareTeam, CareTeamParticipant
from aidbox.hl7_fhir_r4_core.search_parameter import SearchParameter, SearchParameterComponent
from aidbox.hl7_fhir_r4_core.healthcare_service import \
    HealthcareService, HealthcareServiceAvailableTime, HealthcareServiceEligibility, HealthcareServiceNotAvailable
from aidbox.hl7_fhir_r4_core.service_request import ServiceRequest
from aidbox.hl7_fhir_r4_core.vision_prescription import \
    VisionPrescription, VisionPrescriptionLensSpecification, VisionPrescriptionLensSpecificationPrism
from aidbox.hl7_fhir_r4_core.claim_response import \
    ClaimResponse, ClaimResponseAddItem, ClaimResponseAddItemDetail, ClaimResponseAddItemDetailSubDetail, \
    ClaimResponseError, ClaimResponseInsurance, ClaimResponseItem, ClaimResponseItemAdjudication, ClaimResponseItemDetail, \
    ClaimResponseItemDetailSubDetail, ClaimResponsePayment, ClaimResponseProcessNote, ClaimResponseTotal
from aidbox.hl7_fhir_r4_core.code_system import \
    CodeSystem, CodeSystemConcept, CodeSystemConceptDesignation, CodeSystemConceptProperty, CodeSystemFilter, \
    CodeSystemProperty
from aidbox.hl7_fhir_r4_core.charge_item_definition import \
    ChargeItemDefinition, ChargeItemDefinitionApplicability, ChargeItemDefinitionPropertyGroup, ChargeItemDefinitionPropertyGroupPriceComponent
from aidbox.hl7_fhir_r4_core.medicinal_product import \
    MedicinalProduct, MedicinalProductManufacturingBusinessOperation, MedicinalProductName, MedicinalProductNameCountryLanguage, \
    MedicinalProductNameNamePart, MedicinalProductSpecialDesignation
from aidbox.hl7_fhir_r4_core.capability_statement import \
    CapabilityStatement, CapabilityStatementDocument, CapabilityStatementImplementation, CapabilityStatementMessaging, \
    CapabilityStatementMessagingEndpoint, CapabilityStatementMessagingSupportedMessage, CapabilityStatementRest, \
    CapabilityStatementRestInteraction, CapabilityStatementRestResource, CapabilityStatementRestResourceInteraction, \
    CapabilityStatementRestResourceOperation, CapabilityStatementRestResourceSearchParam, CapabilityStatementRestSecurity, \
    CapabilityStatementSoftware
from aidbox.hl7_fhir_r4_core.care_plan import CarePlan, CarePlanActivity, CarePlanActivityDetail
from aidbox.hl7_fhir_r4_core.observation_definition import \
    ObservationDefinition, ObservationDefinitionQualifiedInterval, ObservationDefinitionQuantitativeDetails
from aidbox.hl7_fhir_r4_core.questionnaire_response import \
    QuestionnaireResponse, QuestionnaireResponseItem, QuestionnaireResponseItemAnswer
from aidbox.hl7_fhir_r4_core.medicinal_product_ingredient import \
    MedicinalProductIngredient, MedicinalProductIngredientSpecifiedSubstance, MedicinalProductIngredientSpecifiedSubstanceStrength, \
    MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength, MedicinalProductIngredientSubstance
from aidbox.hl7_fhir_r4_core.naming_system import NamingSystem, NamingSystemUniqueId
from aidbox.hl7_fhir_r4_core.medicinal_product_contraindication import \
    MedicinalProductContraindication, MedicinalProductContraindicationOtherTherapy
from aidbox.hl7_fhir_r4_core.patient import \
    Patient, PatientCommunication, PatientContact, PatientLink
from aidbox.hl7_fhir_r4_core.body_structure import BodyStructure
from aidbox.hl7_fhir_r4_core.condition import Condition, ConditionEvidence, ConditionStage
from aidbox.hl7_fhir_r4_core.research_element_definition import \
    ResearchElementDefinition, ResearchElementDefinitionCharacteristic
from aidbox.hl7_fhir_r4_core.enrollment_request import EnrollmentRequest
from aidbox.hl7_fhir_r4_core.medication_dispense import \
    MedicationDispense, MedicationDispensePerformer, MedicationDispenseSubstitution
from aidbox.hl7_fhir_r4_core.terminology_capabilities import \
    TerminologyCapabilities, TerminologyCapabilitiesClosure, TerminologyCapabilitiesCodeSystem, TerminologyCapabilitiesCodeSystemVersion, \
    TerminologyCapabilitiesCodeSystemVersionFilter, TerminologyCapabilitiesExpansion, TerminologyCapabilitiesExpansionParameter, \
    TerminologyCapabilitiesImplementation, TerminologyCapabilitiesSoftware, TerminologyCapabilitiesTranslation, \
    TerminologyCapabilitiesValidateCode
from aidbox.hl7_fhir_r4_core.medication_administration import \
    MedicationAdministration, MedicationAdministrationDosage, MedicationAdministrationPerformer
from aidbox.hl7_fhir_r4_core.task import Task, TaskInput, TaskOutput, TaskRestriction
from aidbox.hl7_fhir_r4_core.appointment import Appointment, AppointmentParticipant
from aidbox.hl7_fhir_r4_core.value_set import \
    ValueSet, ValueSetCompose, ValueSetComposeInclude, ValueSetComposeIncludeConcept, ValueSetComposeIncludeConceptDesignation, \
    ValueSetComposeIncludeFilter, ValueSetExpansion, ValueSetExpansionContains, ValueSetExpansionParameter
from aidbox.hl7_fhir_r4_core.medication import Medication, MedicationBatch, MedicationIngredient
from aidbox.hl7_fhir_r4_core.measure_report import \
    MeasureReport, MeasureReportGroup, MeasureReportGroupPopulation, MeasureReportGroupStratifier, MeasureReportGroupStratifierStratum, \
    MeasureReportGroupStratifierStratumComponent, MeasureReportGroupStratifierStratumPopulation
from aidbox.hl7_fhir_r4_core.medicinal_product_packaged import \
    MedicinalProductPackaged, MedicinalProductPackagedBatchIdentifier, MedicinalProductPackagedPackageItem
from aidbox.hl7_fhir_r4_core.specimen import \
    Specimen, SpecimenCollection, SpecimenContainer, SpecimenProcessing
from aidbox.hl7_fhir_r4_core.medicinal_product_interaction import \
    MedicinalProductInteraction, MedicinalProductInteractionInteractant
from aidbox.hl7_fhir_r4_core.device_use_statement import DeviceUseStatement
from aidbox.hl7_fhir_r4_core.supply_delivery import SupplyDelivery, SupplyDeliverySuppliedItem
from aidbox.hl7_fhir_r4_core.binary import Binary
from aidbox.hl7_fhir_r4_core.account import Account, AccountCoverage, AccountGuarantor
from aidbox.hl7_fhir_r4_core.substance_protein import SubstanceProtein, SubstanceProteinSubunit
from aidbox.hl7_fhir_r4_core.medication_statement import MedicationStatement
from aidbox.hl7_fhir_r4_core.adverse_event import \
    AdverseEvent, AdverseEventSuspectEntity, AdverseEventSuspectEntityCausality
from aidbox.hl7_fhir_r4_core.consent import \
    Consent, ConsentPolicy, ConsentProvision, ConsentProvisionActor, ConsentProvisionData, ConsentVerification
from aidbox.hl7_fhir_r4_core.structure_definition import \
    StructureDefinition, StructureDefinitionContext, StructureDefinitionDifferential, StructureDefinitionMapping, \
    StructureDefinitionSnapshot
from aidbox.hl7_fhir_r4_core.document_reference import \
    DocumentReference, DocumentReferenceContent, DocumentReferenceContext, DocumentReferenceRelatesTo
from aidbox.hl7_fhir_r4_core.evidence import Evidence
from aidbox.hl7_fhir_r4_core.event_definition import EventDefinition
from aidbox.hl7_fhir_r4_core.practitioner_role import \
    PractitionerRole, PractitionerRoleAvailableTime, PractitionerRoleNotAvailable
from aidbox.hl7_fhir_r4_core.medicinal_product_pharmaceutical import \
    MedicinalProductPharmaceutical, MedicinalProductPharmaceuticalCharacteristics, MedicinalProductPharmaceuticalRouteOfAdministration, \
    MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies, MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod
from aidbox.hl7_fhir_r4_core.organization import Organization, OrganizationContact
from aidbox.hl7_fhir_r4_core.payment_notice import PaymentNotice
from aidbox.hl7_fhir_r4_core.verification_result import \
    VerificationResult, VerificationResultAttestation, VerificationResultPrimarySource, VerificationResultValidator
from aidbox.hl7_fhir_r4_core.allergy_intolerance import \
    AllergyIntolerance, AllergyIntoleranceReaction
from aidbox.hl7_fhir_r4_core.insurance_plan import \
    InsurancePlan, InsurancePlanContact, InsurancePlanCoverage, InsurancePlanCoverageBenefit, InsurancePlanCoverageBenefitLimit, \
    InsurancePlanPlan, InsurancePlanPlanGeneralCost, InsurancePlanPlanSpecificCost, InsurancePlanPlanSpecificCostBenefit, \
    InsurancePlanPlanSpecificCostBenefitCost
from aidbox.hl7_fhir_r4_core.claim import \
    Claim, ClaimAccident, ClaimCareTeam, ClaimDiagnosis, ClaimInsurance, ClaimItem, ClaimItemDetail, ClaimItemDetailSubDetail, \
    ClaimPayee, ClaimProcedure, ClaimRelated, ClaimSupportingInfo
from aidbox.hl7_fhir_r4_core.immunization import \
    Immunization, ImmunizationEducation, ImmunizationPerformer, ImmunizationProtocolApplied, ImmunizationReaction
from aidbox.hl7_fhir_r4_core.audit_event import \
    AuditEvent, AuditEventAgent, AuditEventAgentNetwork, AuditEventEntity, AuditEventEntityDetail, AuditEventSource
from aidbox.hl7_fhir_r4_core.invoice import \
    Invoice, InvoiceLineItem, InvoiceLineItemPriceComponent, InvoiceParticipant
from aidbox.hl7_fhir_r4_core.activity_definition import \
    ActivityDefinition, ActivityDefinitionDynamicValue, ActivityDefinitionParticipant
from aidbox.hl7_fhir_r4_core.substance_nucleic_acid import \
    SubstanceNucleicAcid, SubstanceNucleicAcidSubunit, SubstanceNucleicAcidSubunitLinkage, SubstanceNucleicAcidSubunitSugar
from aidbox.hl7_fhir_r4_core.library import Library
from aidbox.hl7_fhir_r4_core.risk_evidence_synthesis import \
    RiskEvidenceSynthesis, RiskEvidenceSynthesisCertainty, RiskEvidenceSynthesisCertaintyCertaintySubcomponent, \
    RiskEvidenceSynthesisRiskEstimate, RiskEvidenceSynthesisRiskEstimatePrecisionEstimate, RiskEvidenceSynthesisSampleSize
from aidbox.hl7_fhir_r4_core.medication_request import \
    MedicationRequest, MedicationRequestDispenseRequest, MedicationRequestDispenseRequestInitialFill, MedicationRequestSubstitution
from aidbox.hl7_fhir_r4_core.request_group import \
    RequestGroup, RequestGroupAction, RequestGroupActionCondition, RequestGroupActionRelatedAction
from aidbox.hl7_fhir_r4_core.linkage import Linkage, LinkageItem
from aidbox.hl7_fhir_r4_core.substance_polymer import \
    SubstancePolymer, SubstancePolymerMonomerSet, SubstancePolymerMonomerSetStartingMaterial, SubstancePolymerRepeat, \
    SubstancePolymerRepeatRepeatUnit, SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation, SubstancePolymerRepeatRepeatUnitStructuralRepresentation
from aidbox.hl7_fhir_r4_core.evidence_variable import \
    EvidenceVariable, EvidenceVariableCharacteristic
from aidbox.hl7_fhir_r4_core.coverage_eligibility_request import \
    CoverageEligibilityRequest, CoverageEligibilityRequestInsurance, CoverageEligibilityRequestItem, CoverageEligibilityRequestItemDiagnosis, \
    CoverageEligibilityRequestSupportingInfo
from aidbox.hl7_fhir_r4_core.medicinal_product_indication import \
    MedicinalProductIndication, MedicinalProductIndicationOtherTherapy
from aidbox.hl7_fhir_r4_core.test_script import \
    TestScript, TestScriptDestination, TestScriptFixture, TestScriptMetadata, TestScriptMetadataCapability, \
    TestScriptMetadataLink, TestScriptOrigin, TestScriptSetup, TestScriptSetupAction, TestScriptSetupActionAssert, \
    TestScriptSetupActionOperation, TestScriptSetupActionOperationRequestHeader, TestScriptTeardown, TestScriptTeardownAction, \
    TestScriptTest, TestScriptTestAction, TestScriptVariable
from aidbox.hl7_fhir_r4_core.supply_request import SupplyRequest, SupplyRequestParameter
from aidbox.hl7_fhir_r4_core.immunization_evaluation import ImmunizationEvaluation

from aidbox.undefined.tutor_notification import TutorNotification
from aidbox.undefined.tutor_notification_template import TutorNotificationTemplate

Account.model_rebuild()
AccountCoverage.model_rebuild()
AccountGuarantor.model_rebuild()
ActivityDefinition.model_rebuild()
ActivityDefinitionDynamicValue.model_rebuild()
ActivityDefinitionParticipant.model_rebuild()
Address.model_rebuild()
AdverseEvent.model_rebuild()
AdverseEventSuspectEntity.model_rebuild()
AdverseEventSuspectEntityCausality.model_rebuild()
Age.model_rebuild()
AllergyIntolerance.model_rebuild()
AllergyIntoleranceReaction.model_rebuild()
Annotation.model_rebuild()
Appointment.model_rebuild()
AppointmentParticipant.model_rebuild()
AppointmentResponse.model_rebuild()
Attachment.model_rebuild()
AuditEvent.model_rebuild()
AuditEventAgent.model_rebuild()
AuditEventAgentNetwork.model_rebuild()
AuditEventEntity.model_rebuild()
AuditEventEntityDetail.model_rebuild()
AuditEventSource.model_rebuild()
BackboneElement.model_rebuild()
Basic.model_rebuild()
Binary.model_rebuild()
BiologicallyDerivedProduct.model_rebuild()
BiologicallyDerivedProductCollection.model_rebuild()
BiologicallyDerivedProductManipulation.model_rebuild()
BiologicallyDerivedProductProcessing.model_rebuild()
BiologicallyDerivedProductStorage.model_rebuild()
BodyStructure.model_rebuild()
Bundle.model_rebuild()
BundleEntry.model_rebuild()
BundleEntryRequest.model_rebuild()
BundleEntryResponse.model_rebuild()
BundleEntrySearch.model_rebuild()
BundleLink.model_rebuild()
CapabilityStatement.model_rebuild()
CapabilityStatementDocument.model_rebuild()
CapabilityStatementImplementation.model_rebuild()
CapabilityStatementMessaging.model_rebuild()
CapabilityStatementMessagingEndpoint.model_rebuild()
CapabilityStatementMessagingSupportedMessage.model_rebuild()
CapabilityStatementRest.model_rebuild()
CapabilityStatementRestInteraction.model_rebuild()
CapabilityStatementRestResource.model_rebuild()
CapabilityStatementRestResourceInteraction.model_rebuild()
CapabilityStatementRestResourceOperation.model_rebuild()
CapabilityStatementRestResourceSearchParam.model_rebuild()
CapabilityStatementRestSecurity.model_rebuild()
CapabilityStatementSoftware.model_rebuild()
CarePlan.model_rebuild()
CarePlanActivity.model_rebuild()
CarePlanActivityDetail.model_rebuild()
CareTeam.model_rebuild()
CareTeamParticipant.model_rebuild()
CatalogEntry.model_rebuild()
CatalogEntryRelatedEntry.model_rebuild()
ChargeItem.model_rebuild()
ChargeItemDefinition.model_rebuild()
ChargeItemDefinitionApplicability.model_rebuild()
ChargeItemDefinitionPropertyGroup.model_rebuild()
ChargeItemDefinitionPropertyGroupPriceComponent.model_rebuild()
ChargeItemPerformer.model_rebuild()
Claim.model_rebuild()
ClaimAccident.model_rebuild()
ClaimCareTeam.model_rebuild()
ClaimDiagnosis.model_rebuild()
ClaimInsurance.model_rebuild()
ClaimItem.model_rebuild()
ClaimItemDetail.model_rebuild()
ClaimItemDetailSubDetail.model_rebuild()
ClaimPayee.model_rebuild()
ClaimProcedure.model_rebuild()
ClaimRelated.model_rebuild()
ClaimResponse.model_rebuild()
ClaimResponseAddItem.model_rebuild()
ClaimResponseAddItemDetail.model_rebuild()
ClaimResponseAddItemDetailSubDetail.model_rebuild()
ClaimResponseError.model_rebuild()
ClaimResponseInsurance.model_rebuild()
ClaimResponseItem.model_rebuild()
ClaimResponseItemAdjudication.model_rebuild()
ClaimResponseItemDetail.model_rebuild()
ClaimResponseItemDetailSubDetail.model_rebuild()
ClaimResponsePayment.model_rebuild()
ClaimResponseProcessNote.model_rebuild()
ClaimResponseTotal.model_rebuild()
ClaimSupportingInfo.model_rebuild()
ClinicalImpression.model_rebuild()
ClinicalImpressionFinding.model_rebuild()
ClinicalImpressionInvestigation.model_rebuild()
CodeSystem.model_rebuild()
CodeSystemConcept.model_rebuild()
CodeSystemConceptDesignation.model_rebuild()
CodeSystemConceptProperty.model_rebuild()
CodeSystemFilter.model_rebuild()
CodeSystemProperty.model_rebuild()
CodeableConcept.model_rebuild()
Coding.model_rebuild()
Communication.model_rebuild()
CommunicationPayload.model_rebuild()
CommunicationRequest.model_rebuild()
CommunicationRequestPayload.model_rebuild()
CompartmentDefinition.model_rebuild()
CompartmentDefinitionResource.model_rebuild()
Composition.model_rebuild()
CompositionAttester.model_rebuild()
CompositionEvent.model_rebuild()
CompositionRelatesTo.model_rebuild()
CompositionSection.model_rebuild()
ConceptMap.model_rebuild()
ConceptMapGroup.model_rebuild()
ConceptMapGroupElement.model_rebuild()
ConceptMapGroupElementTarget.model_rebuild()
ConceptMapGroupElementTargetDependsOn.model_rebuild()
ConceptMapGroupUnmapped.model_rebuild()
Condition.model_rebuild()
ConditionEvidence.model_rebuild()
ConditionStage.model_rebuild()
Consent.model_rebuild()
ConsentPolicy.model_rebuild()
ConsentProvision.model_rebuild()
ConsentProvisionActor.model_rebuild()
ConsentProvisionData.model_rebuild()
ConsentVerification.model_rebuild()
ContactDetail.model_rebuild()
ContactPoint.model_rebuild()
Contract.model_rebuild()
ContractContentDefinition.model_rebuild()
ContractFriendly.model_rebuild()
ContractLegal.model_rebuild()
ContractRule.model_rebuild()
ContractSigner.model_rebuild()
ContractTerm.model_rebuild()
ContractTermAction.model_rebuild()
ContractTermActionSubject.model_rebuild()
ContractTermAsset.model_rebuild()
ContractTermAssetContext.model_rebuild()
ContractTermAssetValuedItem.model_rebuild()
ContractTermOffer.model_rebuild()
ContractTermOfferAnswer.model_rebuild()
ContractTermOfferParty.model_rebuild()
ContractTermSecurityLabel.model_rebuild()
Contributor.model_rebuild()
Count.model_rebuild()
Coverage.model_rebuild()
CoverageClass.model_rebuild()
CoverageCostToBeneficiary.model_rebuild()
CoverageCostToBeneficiaryException.model_rebuild()
CoverageEligibilityRequest.model_rebuild()
CoverageEligibilityRequestInsurance.model_rebuild()
CoverageEligibilityRequestItem.model_rebuild()
CoverageEligibilityRequestItemDiagnosis.model_rebuild()
CoverageEligibilityRequestSupportingInfo.model_rebuild()
CoverageEligibilityResponse.model_rebuild()
CoverageEligibilityResponseError.model_rebuild()
CoverageEligibilityResponseInsurance.model_rebuild()
CoverageEligibilityResponseInsuranceItem.model_rebuild()
CoverageEligibilityResponseInsuranceItemBenefit.model_rebuild()
DataRequirement.model_rebuild()
DetectedIssue.model_rebuild()
DetectedIssueEvidence.model_rebuild()
DetectedIssueMitigation.model_rebuild()
Device.model_rebuild()
DeviceDefinition.model_rebuild()
DeviceDefinitionCapability.model_rebuild()
DeviceDefinitionDeviceName.model_rebuild()
DeviceDefinitionMaterial.model_rebuild()
DeviceDefinitionProperty.model_rebuild()
DeviceDefinitionSpecialization.model_rebuild()
DeviceDefinitionUdiDeviceIdentifier.model_rebuild()
DeviceDeviceName.model_rebuild()
DeviceMetric.model_rebuild()
DeviceMetricCalibration.model_rebuild()
DeviceProperty.model_rebuild()
DeviceRequest.model_rebuild()
DeviceRequestParameter.model_rebuild()
DeviceSpecialization.model_rebuild()
DeviceUdiCarrier.model_rebuild()
DeviceUseStatement.model_rebuild()
DeviceVersion.model_rebuild()
DiagnosticReport.model_rebuild()
DiagnosticReportMedia.model_rebuild()
Distance.model_rebuild()
DocumentManifest.model_rebuild()
DocumentManifestRelated.model_rebuild()
DocumentReference.model_rebuild()
DocumentReferenceContent.model_rebuild()
DocumentReferenceContext.model_rebuild()
DocumentReferenceRelatesTo.model_rebuild()
DomainResource.model_rebuild()
Dosage.model_rebuild()
Duration.model_rebuild()
EffectEvidenceSynthesis.model_rebuild()
EffectEvidenceSynthesisCertainty.model_rebuild()
EffectEvidenceSynthesisCertaintyCertaintySubcomponent.model_rebuild()
EffectEvidenceSynthesisEffectEstimate.model_rebuild()
EffectEvidenceSynthesisEffectEstimatePrecisionEstimate.model_rebuild()
EffectEvidenceSynthesisResultsByExposure.model_rebuild()
EffectEvidenceSynthesisSampleSize.model_rebuild()
Element.model_rebuild()
ElementDefinition.model_rebuild()
Encounter.model_rebuild()
EncounterClassHistory.model_rebuild()
EncounterDiagnosis.model_rebuild()
EncounterHospitalization.model_rebuild()
EncounterLocation.model_rebuild()
EncounterParticipant.model_rebuild()
EncounterStatusHistory.model_rebuild()
Endpoint.model_rebuild()
EnrollmentRequest.model_rebuild()
EnrollmentResponse.model_rebuild()
EpisodeOfCare.model_rebuild()
EpisodeOfCareDiagnosis.model_rebuild()
EpisodeOfCareStatusHistory.model_rebuild()
EventDefinition.model_rebuild()
Evidence.model_rebuild()
EvidenceVariable.model_rebuild()
EvidenceVariableCharacteristic.model_rebuild()
ExampleScenario.model_rebuild()
ExampleScenarioActor.model_rebuild()
ExampleScenarioInstance.model_rebuild()
ExampleScenarioInstanceContainedInstance.model_rebuild()
ExampleScenarioInstanceVersion.model_rebuild()
ExampleScenarioProcess.model_rebuild()
ExampleScenarioProcessStep.model_rebuild()
ExampleScenarioProcessStepAlternative.model_rebuild()
ExampleScenarioProcessStepOperation.model_rebuild()
ExplanationOfBenefit.model_rebuild()
ExplanationOfBenefitAccident.model_rebuild()
ExplanationOfBenefitAddItem.model_rebuild()
ExplanationOfBenefitAddItemDetail.model_rebuild()
ExplanationOfBenefitAddItemDetailSubDetail.model_rebuild()
ExplanationOfBenefitBenefitBalance.model_rebuild()
ExplanationOfBenefitBenefitBalanceFinancial.model_rebuild()
ExplanationOfBenefitCareTeam.model_rebuild()
ExplanationOfBenefitDiagnosis.model_rebuild()
ExplanationOfBenefitInsurance.model_rebuild()
ExplanationOfBenefitItem.model_rebuild()
ExplanationOfBenefitItemAdjudication.model_rebuild()
ExplanationOfBenefitItemDetail.model_rebuild()
ExplanationOfBenefitItemDetailSubDetail.model_rebuild()
ExplanationOfBenefitPayee.model_rebuild()
ExplanationOfBenefitPayment.model_rebuild()
ExplanationOfBenefitProcedure.model_rebuild()
ExplanationOfBenefitProcessNote.model_rebuild()
ExplanationOfBenefitRelated.model_rebuild()
ExplanationOfBenefitSupportingInfo.model_rebuild()
ExplanationOfBenefitTotal.model_rebuild()
Expression.model_rebuild()
Extension.model_rebuild()
FamilyMemberHistory.model_rebuild()
FamilyMemberHistoryCondition.model_rebuild()
Flag.model_rebuild()
Goal.model_rebuild()
GoalTarget.model_rebuild()
GraphDefinition.model_rebuild()
GraphDefinitionLink.model_rebuild()
GraphDefinitionLinkTarget.model_rebuild()
GraphDefinitionLinkTargetCompartment.model_rebuild()
Group.model_rebuild()
GroupCharacteristic.model_rebuild()
GroupMember.model_rebuild()
GuidanceResponse.model_rebuild()
HealthcareService.model_rebuild()
HealthcareServiceAvailableTime.model_rebuild()
HealthcareServiceEligibility.model_rebuild()
HealthcareServiceNotAvailable.model_rebuild()
HumanName.model_rebuild()
Identifier.model_rebuild()
ImagingStudy.model_rebuild()
ImagingStudySeries.model_rebuild()
ImagingStudySeriesInstance.model_rebuild()
ImagingStudySeriesPerformer.model_rebuild()
Immunization.model_rebuild()
ImmunizationEducation.model_rebuild()
ImmunizationEvaluation.model_rebuild()
ImmunizationPerformer.model_rebuild()
ImmunizationProtocolApplied.model_rebuild()
ImmunizationReaction.model_rebuild()
ImmunizationRecommendation.model_rebuild()
ImmunizationRecommendationRecommendation.model_rebuild()
ImmunizationRecommendationRecommendationDateCriterion.model_rebuild()
ImplementationGuide.model_rebuild()
ImplementationGuideDefinition.model_rebuild()
ImplementationGuideDefinitionGrouping.model_rebuild()
ImplementationGuideDefinitionPage.model_rebuild()
ImplementationGuideDefinitionParameter.model_rebuild()
ImplementationGuideDefinitionResource.model_rebuild()
ImplementationGuideDefinitionTemplate.model_rebuild()
ImplementationGuideDependsOn.model_rebuild()
ImplementationGuideGlobal.model_rebuild()
ImplementationGuideManifest.model_rebuild()
ImplementationGuideManifestPage.model_rebuild()
ImplementationGuideManifestResource.model_rebuild()
InsurancePlan.model_rebuild()
InsurancePlanContact.model_rebuild()
InsurancePlanCoverage.model_rebuild()
InsurancePlanCoverageBenefit.model_rebuild()
InsurancePlanCoverageBenefitLimit.model_rebuild()
InsurancePlanPlan.model_rebuild()
InsurancePlanPlanGeneralCost.model_rebuild()
InsurancePlanPlanSpecificCost.model_rebuild()
InsurancePlanPlanSpecificCostBenefit.model_rebuild()
InsurancePlanPlanSpecificCostBenefitCost.model_rebuild()
Invoice.model_rebuild()
InvoiceLineItem.model_rebuild()
InvoiceLineItemPriceComponent.model_rebuild()
InvoiceParticipant.model_rebuild()
Library.model_rebuild()
Linkage.model_rebuild()
LinkageItem.model_rebuild()
List.model_rebuild()
ListEntry.model_rebuild()
Location.model_rebuild()
LocationHoursOfOperation.model_rebuild()
LocationPosition.model_rebuild()
MarketingStatus.model_rebuild()
Measure.model_rebuild()
MeasureGroup.model_rebuild()
MeasureGroupPopulation.model_rebuild()
MeasureGroupStratifier.model_rebuild()
MeasureGroupStratifierComponent.model_rebuild()
MeasureReport.model_rebuild()
MeasureReportGroup.model_rebuild()
MeasureReportGroupPopulation.model_rebuild()
MeasureReportGroupStratifier.model_rebuild()
MeasureReportGroupStratifierStratum.model_rebuild()
MeasureReportGroupStratifierStratumComponent.model_rebuild()
MeasureReportGroupStratifierStratumPopulation.model_rebuild()
MeasureSupplementalData.model_rebuild()
Media.model_rebuild()
Medication.model_rebuild()
MedicationAdministration.model_rebuild()
MedicationAdministrationDosage.model_rebuild()
MedicationAdministrationPerformer.model_rebuild()
MedicationBatch.model_rebuild()
MedicationDispense.model_rebuild()
MedicationDispensePerformer.model_rebuild()
MedicationDispenseSubstitution.model_rebuild()
MedicationIngredient.model_rebuild()
MedicationKnowledge.model_rebuild()
MedicationKnowledgeAdministrationGuidelines.model_rebuild()
MedicationKnowledgeAdministrationGuidelinesDosage.model_rebuild()
MedicationKnowledgeAdministrationGuidelinesPatientCharacteristics.model_rebuild()
MedicationKnowledgeCost.model_rebuild()
MedicationKnowledgeDrugCharacteristic.model_rebuild()
MedicationKnowledgeIngredient.model_rebuild()
MedicationKnowledgeKinetics.model_rebuild()
MedicationKnowledgeMedicineClassification.model_rebuild()
MedicationKnowledgeMonitoringProgram.model_rebuild()
MedicationKnowledgeMonograph.model_rebuild()
MedicationKnowledgePackaging.model_rebuild()
MedicationKnowledgeRegulatory.model_rebuild()
MedicationKnowledgeRegulatoryMaxDispense.model_rebuild()
MedicationKnowledgeRegulatorySchedule.model_rebuild()
MedicationKnowledgeRegulatorySubstitution.model_rebuild()
MedicationKnowledgeRelatedMedicationKnowledge.model_rebuild()
MedicationRequest.model_rebuild()
MedicationRequestDispenseRequest.model_rebuild()
MedicationRequestDispenseRequestInitialFill.model_rebuild()
MedicationRequestSubstitution.model_rebuild()
MedicationStatement.model_rebuild()
MedicinalProduct.model_rebuild()
MedicinalProductAuthorization.model_rebuild()
MedicinalProductAuthorizationJurisdictionalAuthorization.model_rebuild()
MedicinalProductAuthorizationProcedure.model_rebuild()
MedicinalProductContraindication.model_rebuild()
MedicinalProductContraindicationOtherTherapy.model_rebuild()
MedicinalProductIndication.model_rebuild()
MedicinalProductIndicationOtherTherapy.model_rebuild()
MedicinalProductIngredient.model_rebuild()
MedicinalProductIngredientSpecifiedSubstance.model_rebuild()
MedicinalProductIngredientSpecifiedSubstanceStrength.model_rebuild()
MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength.model_rebuild()
MedicinalProductIngredientSubstance.model_rebuild()
MedicinalProductInteraction.model_rebuild()
MedicinalProductInteractionInteractant.model_rebuild()
MedicinalProductManufactured.model_rebuild()
MedicinalProductManufacturingBusinessOperation.model_rebuild()
MedicinalProductName.model_rebuild()
MedicinalProductNameCountryLanguage.model_rebuild()
MedicinalProductNameNamePart.model_rebuild()
MedicinalProductPackaged.model_rebuild()
MedicinalProductPackagedBatchIdentifier.model_rebuild()
MedicinalProductPackagedPackageItem.model_rebuild()
MedicinalProductPharmaceutical.model_rebuild()
MedicinalProductPharmaceuticalCharacteristics.model_rebuild()
MedicinalProductPharmaceuticalRouteOfAdministration.model_rebuild()
MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies.model_rebuild()
MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod.model_rebuild()
MedicinalProductSpecialDesignation.model_rebuild()
MedicinalProductUndesirableEffect.model_rebuild()
MessageDefinition.model_rebuild()
MessageDefinitionAllowedResponse.model_rebuild()
MessageDefinitionFocus.model_rebuild()
MessageHeader.model_rebuild()
MessageHeaderDestination.model_rebuild()
MessageHeaderResponse.model_rebuild()
MessageHeaderSource.model_rebuild()
Meta.model_rebuild()
MolecularSequence.model_rebuild()
MolecularSequenceQuality.model_rebuild()
MolecularSequenceQualityRoc.model_rebuild()
MolecularSequenceReferenceSeq.model_rebuild()
MolecularSequenceRepository.model_rebuild()
MolecularSequenceStructureVariant.model_rebuild()
MolecularSequenceStructureVariantInner.model_rebuild()
MolecularSequenceStructureVariantOuter.model_rebuild()
MolecularSequenceVariant.model_rebuild()
Money.model_rebuild()
NamingSystem.model_rebuild()
NamingSystemUniqueId.model_rebuild()
Narrative.model_rebuild()
NutritionOrder.model_rebuild()
NutritionOrderEnteralFormula.model_rebuild()
NutritionOrderEnteralFormulaAdministration.model_rebuild()
NutritionOrderOralDiet.model_rebuild()
NutritionOrderOralDietNutrient.model_rebuild()
NutritionOrderOralDietTexture.model_rebuild()
NutritionOrderSupplement.model_rebuild()
Observation.model_rebuild()
ObservationComponent.model_rebuild()
ObservationDefinition.model_rebuild()
ObservationDefinitionQualifiedInterval.model_rebuild()
ObservationDefinitionQuantitativeDetails.model_rebuild()
ObservationReferenceRange.model_rebuild()
OperationDefinition.model_rebuild()
OperationDefinitionOverload.model_rebuild()
OperationDefinitionParameter.model_rebuild()
OperationDefinitionParameterBinding.model_rebuild()
OperationDefinitionParameterReferencedFrom.model_rebuild()
OperationOutcome.model_rebuild()
OperationOutcomeIssue.model_rebuild()
Organization.model_rebuild()
OrganizationAffiliation.model_rebuild()
OrganizationContact.model_rebuild()
ParameterDefinition.model_rebuild()
Parameters.model_rebuild()
ParametersParameter.model_rebuild()
Patient.model_rebuild()
PatientCommunication.model_rebuild()
PatientContact.model_rebuild()
PatientLink.model_rebuild()
PaymentNotice.model_rebuild()
PaymentReconciliation.model_rebuild()
PaymentReconciliationDetail.model_rebuild()
PaymentReconciliationProcessNote.model_rebuild()
Period.model_rebuild()
Person.model_rebuild()
PersonLink.model_rebuild()
PlanDefinition.model_rebuild()
PlanDefinitionAction.model_rebuild()
PlanDefinitionActionCondition.model_rebuild()
PlanDefinitionActionDynamicValue.model_rebuild()
PlanDefinitionActionParticipant.model_rebuild()
PlanDefinitionActionRelatedAction.model_rebuild()
PlanDefinitionGoal.model_rebuild()
PlanDefinitionGoalTarget.model_rebuild()
Population.model_rebuild()
Practitioner.model_rebuild()
PractitionerQualification.model_rebuild()
PractitionerRole.model_rebuild()
PractitionerRoleAvailableTime.model_rebuild()
PractitionerRoleNotAvailable.model_rebuild()
Procedure.model_rebuild()
ProcedureFocalDevice.model_rebuild()
ProcedurePerformer.model_rebuild()
ProdCharacteristic.model_rebuild()
ProductShelfLife.model_rebuild()
Provenance.model_rebuild()
ProvenanceAgent.model_rebuild()
ProvenanceEntity.model_rebuild()
Quantity.model_rebuild()
Questionnaire.model_rebuild()
QuestionnaireItem.model_rebuild()
QuestionnaireItemAnswerOption.model_rebuild()
QuestionnaireItemEnableWhen.model_rebuild()
QuestionnaireItemInitial.model_rebuild()
QuestionnaireResponse.model_rebuild()
QuestionnaireResponseItem.model_rebuild()
QuestionnaireResponseItemAnswer.model_rebuild()
Range.model_rebuild()
Ratio.model_rebuild()
Reference.model_rebuild()
RelatedArtifact.model_rebuild()
RelatedPerson.model_rebuild()
RelatedPersonCommunication.model_rebuild()
RequestGroup.model_rebuild()
RequestGroupAction.model_rebuild()
RequestGroupActionCondition.model_rebuild()
RequestGroupActionRelatedAction.model_rebuild()
ResearchDefinition.model_rebuild()
ResearchElementDefinition.model_rebuild()
ResearchElementDefinitionCharacteristic.model_rebuild()
ResearchStudy.model_rebuild()
ResearchStudyArm.model_rebuild()
ResearchStudyObjective.model_rebuild()
ResearchSubject.model_rebuild()
Resource.model_rebuild()
RiskAssessment.model_rebuild()
RiskAssessmentPrediction.model_rebuild()
RiskEvidenceSynthesis.model_rebuild()
RiskEvidenceSynthesisCertainty.model_rebuild()
RiskEvidenceSynthesisCertaintyCertaintySubcomponent.model_rebuild()
RiskEvidenceSynthesisRiskEstimate.model_rebuild()
RiskEvidenceSynthesisRiskEstimatePrecisionEstimate.model_rebuild()
RiskEvidenceSynthesisSampleSize.model_rebuild()
SampledData.model_rebuild()
Schedule.model_rebuild()
SearchParameter.model_rebuild()
SearchParameterComponent.model_rebuild()
ServiceRequest.model_rebuild()
Signature.model_rebuild()
Slot.model_rebuild()
Specimen.model_rebuild()
SpecimenCollection.model_rebuild()
SpecimenContainer.model_rebuild()
SpecimenDefinition.model_rebuild()
SpecimenDefinitionTypeTested.model_rebuild()
SpecimenDefinitionTypeTestedContainer.model_rebuild()
SpecimenDefinitionTypeTestedContainerAdditive.model_rebuild()
SpecimenDefinitionTypeTestedHandling.model_rebuild()
SpecimenProcessing.model_rebuild()
StructureDefinition.model_rebuild()
StructureDefinitionContext.model_rebuild()
StructureDefinitionDifferential.model_rebuild()
StructureDefinitionMapping.model_rebuild()
StructureDefinitionSnapshot.model_rebuild()
StructureMap.model_rebuild()
StructureMapGroup.model_rebuild()
StructureMapGroupInput.model_rebuild()
StructureMapGroupRule.model_rebuild()
StructureMapGroupRuleDependent.model_rebuild()
StructureMapGroupRuleSource.model_rebuild()
StructureMapGroupRuleTarget.model_rebuild()
StructureMapGroupRuleTargetParameter.model_rebuild()
StructureMapStructure.model_rebuild()
Subscription.model_rebuild()
SubscriptionChannel.model_rebuild()
Substance.model_rebuild()
SubstanceAmount.model_rebuild()
SubstanceIngredient.model_rebuild()
SubstanceInstance.model_rebuild()
SubstanceNucleicAcid.model_rebuild()
SubstanceNucleicAcidSubunit.model_rebuild()
SubstanceNucleicAcidSubunitLinkage.model_rebuild()
SubstanceNucleicAcidSubunitSugar.model_rebuild()
SubstancePolymer.model_rebuild()
SubstancePolymerMonomerSet.model_rebuild()
SubstancePolymerMonomerSetStartingMaterial.model_rebuild()
SubstancePolymerRepeat.model_rebuild()
SubstancePolymerRepeatRepeatUnit.model_rebuild()
SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation.model_rebuild()
SubstancePolymerRepeatRepeatUnitStructuralRepresentation.model_rebuild()
SubstanceProtein.model_rebuild()
SubstanceProteinSubunit.model_rebuild()
SubstanceReferenceInformation.model_rebuild()
SubstanceReferenceInformationClassification.model_rebuild()
SubstanceReferenceInformationGene.model_rebuild()
SubstanceReferenceInformationGeneElement.model_rebuild()
SubstanceReferenceInformationTarget.model_rebuild()
SubstanceSourceMaterial.model_rebuild()
SubstanceSourceMaterialFractionDescription.model_rebuild()
SubstanceSourceMaterialOrganism.model_rebuild()
SubstanceSourceMaterialOrganismAuthor.model_rebuild()
SubstanceSourceMaterialOrganismHybrid.model_rebuild()
SubstanceSourceMaterialOrganismOrganismGeneral.model_rebuild()
SubstanceSourceMaterialPartDescription.model_rebuild()
SubstanceSpecification.model_rebuild()
SubstanceSpecificationCode.model_rebuild()
SubstanceSpecificationMoiety.model_rebuild()
SubstanceSpecificationName.model_rebuild()
SubstanceSpecificationNameOfficial.model_rebuild()
SubstanceSpecificationProperty.model_rebuild()
SubstanceSpecificationRelationship.model_rebuild()
SubstanceSpecificationStructure.model_rebuild()
SubstanceSpecificationStructureIsotope.model_rebuild()
SubstanceSpecificationStructureIsotopeMolecularWeight.model_rebuild()
SubstanceSpecificationStructureRepresentation.model_rebuild()
SupplyDelivery.model_rebuild()
SupplyDeliverySuppliedItem.model_rebuild()
SupplyRequest.model_rebuild()
SupplyRequestParameter.model_rebuild()
Task.model_rebuild()
TaskInput.model_rebuild()
TaskOutput.model_rebuild()
TaskRestriction.model_rebuild()
TerminologyCapabilities.model_rebuild()
TerminologyCapabilitiesClosure.model_rebuild()
TerminologyCapabilitiesCodeSystem.model_rebuild()
TerminologyCapabilitiesCodeSystemVersion.model_rebuild()
TerminologyCapabilitiesCodeSystemVersionFilter.model_rebuild()
TerminologyCapabilitiesExpansion.model_rebuild()
TerminologyCapabilitiesExpansionParameter.model_rebuild()
TerminologyCapabilitiesImplementation.model_rebuild()
TerminologyCapabilitiesSoftware.model_rebuild()
TerminologyCapabilitiesTranslation.model_rebuild()
TerminologyCapabilitiesValidateCode.model_rebuild()
TestReport.model_rebuild()
TestReportParticipant.model_rebuild()
TestReportSetup.model_rebuild()
TestReportSetupAction.model_rebuild()
TestReportSetupActionAssert.model_rebuild()
TestReportSetupActionOperation.model_rebuild()
TestReportTeardown.model_rebuild()
TestReportTeardownAction.model_rebuild()
TestReportTest.model_rebuild()
TestReportTestAction.model_rebuild()
TestScript.model_rebuild()
TestScriptDestination.model_rebuild()
TestScriptFixture.model_rebuild()
TestScriptMetadata.model_rebuild()
TestScriptMetadataCapability.model_rebuild()
TestScriptMetadataLink.model_rebuild()
TestScriptOrigin.model_rebuild()
TestScriptSetup.model_rebuild()
TestScriptSetupAction.model_rebuild()
TestScriptSetupActionAssert.model_rebuild()
TestScriptSetupActionOperation.model_rebuild()
TestScriptSetupActionOperationRequestHeader.model_rebuild()
TestScriptTeardown.model_rebuild()
TestScriptTeardownAction.model_rebuild()
TestScriptTest.model_rebuild()
TestScriptTestAction.model_rebuild()
TestScriptVariable.model_rebuild()
Timing.model_rebuild()
TriggerDefinition.model_rebuild()
TutorNotification.model_rebuild()
TutorNotificationTemplate.model_rebuild()
UsageContext.model_rebuild()
ValueSet.model_rebuild()
ValueSetCompose.model_rebuild()
ValueSetComposeInclude.model_rebuild()
ValueSetComposeIncludeConcept.model_rebuild()
ValueSetComposeIncludeConceptDesignation.model_rebuild()
ValueSetComposeIncludeFilter.model_rebuild()
ValueSetExpansion.model_rebuild()
ValueSetExpansionContains.model_rebuild()
ValueSetExpansionParameter.model_rebuild()
VerificationResult.model_rebuild()
VerificationResultAttestation.model_rebuild()
VerificationResultPrimarySource.model_rebuild()
VerificationResultValidator.model_rebuild()
VisionPrescription.model_rebuild()
VisionPrescriptionLensSpecification.model_rebuild()
VisionPrescriptionLensSpecificationPrism.model_rebuild()
