// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { Composition } from '../hl7-fhir-r4-core/Composition';
import { CompositionAttester } from '../hl7-fhir-r4-core/Composition';
import { CompositionEvent } from '../hl7-fhir-r4-core/Composition';
import { CompositionRelatesTo } from '../hl7-fhir-r4-core/Composition';
import { CompositionSection } from '../hl7-fhir-r4-core/Composition';
import { Extension } from '../hl7-fhir-r4-core/Extension';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface Catalog {
    __profileUrl: 'http://hl7.org/fhir/StructureDefinition/catalog';
    
    extension?: Extension[];
    type: CodeableConcept;
    category: CodeableConcept[];
    subject?: Reference<'Resource'>;
    date: string;
    section?: CompositionSection[];
}

export const attach_Catalog = (resource: Composition, profile: Catalog): Composition => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/catalog']
        },
        extension: profile.extension,
        type: profile.type,
        category: profile.category,
        subject: profile.subject,
        date: profile.date,
        section: profile.section,
    }
}

export const extract_Composition = (resource: Composition): Catalog => {
    if (resource.category === undefined) {
        throw new Error("'category' is required for http://hl7.org/fhir/StructureDefinition/catalog");
    }
    
    return {
        __profileUrl: 'http://hl7.org/fhir/StructureDefinition/catalog',
        extension: resource.extension,
        type: resource.type,
        category: resource.category,
        subject: resource.subject,
        date: resource.date,
        section: resource.section,
    }
}
