// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Extension } from '../hl7-fhir-r4-core/Extension';
import { GuidanceResponse } from '../hl7-fhir-r4-core/GuidanceResponse';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface Cdshooksguidanceresponse {
    __profileUrl: 'http://hl7.org/fhir/StructureDefinition/cdshooksguidanceresponse';
    
    extension?: Extension[];
    requestIdentifier: Identifier;
    identifier: Identifier[];
    moduleUri: string;
    subject?: Reference<'Group' | 'Patient'>;
    occurrenceDateTime?: string;
    performer?: Reference<'Device'>;
    result?: Reference<'CarePlan' | 'RequestGroup'>;
}

export const attach_Cdshooksguidanceresponse = (resource: GuidanceResponse, profile: Cdshooksguidanceresponse): GuidanceResponse => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/cdshooksguidanceresponse']
        },
        extension: profile.extension,
        requestIdentifier: profile.requestIdentifier,
        identifier: profile.identifier,
        moduleUri: profile.moduleUri,
        subject: profile.subject,
        occurrenceDateTime: profile.occurrenceDateTime,
        performer: profile.performer,
        result: profile.result,
    }
}
