// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { Coding } from '../hl7-fhir-r4-core/Coding';
import { ContactPoint } from '../hl7-fhir-r4-core/ContactPoint';
import { DomainResource } from '../hl7-fhir-r4-core/DomainResource';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { Period } from '../hl7-fhir-r4-core/Period';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface Endpoint extends DomainResource {
    address: string;
    _address?: Element;
    connectionType: Coding;
    contact?: ContactPoint[];
    header?: string[];
    _header?: Element;
    identifier?: Identifier[];
    managingOrganization?: Reference<'Organization'>;
    name?: string;
    _name?: Element;
    payloadMimeType?: string[];
    _payloadMimeType?: Element;
    payloadType: CodeableConcept[];
    period?: Period;
    status: 'active' | 'suspended' | 'error' | 'off' | 'entered-in-error' | 'test';
    _status?: Element;
}

