// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from '../hl7-fhir-r4-core/Annotation';
import { BackboneElement } from '../hl7-fhir-r4-core/BackboneElement';
import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { ContactDetail } from '../hl7-fhir-r4-core/ContactDetail';
import { DataRequirement } from '../hl7-fhir-r4-core/DataRequirement';
import { DomainResource } from '../hl7-fhir-r4-core/DomainResource';
import { Duration } from '../hl7-fhir-r4-core/Duration';
import { Expression } from '../hl7-fhir-r4-core/Expression';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { Period } from '../hl7-fhir-r4-core/Period';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { RelatedArtifact } from '../hl7-fhir-r4-core/RelatedArtifact';
import { Timing } from '../hl7-fhir-r4-core/Timing';
import { TriggerDefinition } from '../hl7-fhir-r4-core/TriggerDefinition';
import { UsageContext } from '../hl7-fhir-r4-core/UsageContext';
import { Element } from '../hl7-fhir-r4-core/Element';


export interface EvidenceVariableCharacteristic extends BackboneElement {
    definitionCanonical?: string;
    definitionCodeableConcept?: CodeableConcept;
    definitionDataRequirement?: DataRequirement;
    definitionExpression?: Expression;
    definitionReference?: Reference<'Group'>;
    definitionTriggerDefinition?: TriggerDefinition;
    description?: string;
    exclude?: boolean;
    groupMeasure?: 'mean' | 'median' | 'mean-of-mean' | 'mean-of-median' | 'median-of-mean' | 'median-of-median';
    participantEffectiveDateTime?: string;
    participantEffectiveDuration?: Duration;
    participantEffectivePeriod?: Period;
    participantEffectiveTiming?: Timing;
    timeFromStart?: Duration;
    usageContext?: UsageContext[];
}

export interface EvidenceVariable extends DomainResource {
    approvalDate?: string;
    _approvalDate?: Element;
    author?: ContactDetail[];
    characteristic: EvidenceVariableCharacteristic[];
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    name?: string;
    _name?: Element;
    note?: Annotation[];
    publisher?: string;
    _publisher?: Element;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    shortTitle?: string;
    _shortTitle?: Element;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    subtitle?: string;
    _subtitle?: Element;
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    type?: 'dichotomous' | 'continuous' | 'descriptive';
    _type?: Element;
    url?: string;
    _url?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}

