// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from '../hl7-fhir-r4-core/Annotation';
import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { Observation } from '../hl7-fhir-r4-core/Observation';
import { ObservationComponent } from '../hl7-fhir-r4-core/Observation';
import { ObservationReferenceRange } from '../hl7-fhir-r4-core/Observation';
import { Quantity } from '../hl7-fhir-r4-core/Quantity';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface Hdlcholesterol {
    __profileUrl: 'http://hl7.org/fhir/StructureDefinition/hdlcholesterol';
    
    code: CodeableConcept;
    valueQuantity?: Quantity;
    interpretation?: CodeableConcept[];
    note?: Annotation[];
    referenceRange?: ObservationReferenceRange[];
    hasMember?: Reference<'MolecularSequence' | 'Observation' | 'QuestionnaireResponse'>[];
    derivedFrom?: Reference<'DocumentReference' | 'ImagingStudy' | 'Media' | 'MolecularSequence' | 'Observation' | 'QuestionnaireResponse'>[];
}

export const attach_Hdlcholesterol = (resource: Observation, profile: Hdlcholesterol): Observation => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/hdlcholesterol']
        },
        code: profile.code,
        valueQuantity: profile.valueQuantity,
        interpretation: profile.interpretation,
        note: profile.note,
        referenceRange: profile.referenceRange,
        hasMember: profile.hasMember,
        derivedFrom: profile.derivedFrom,
    }
}
