// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Extension } from '../hl7-fhir-r4-core/Extension';
import { Quantity } from '../hl7-fhir-r4-core/Quantity';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface Iso21090PqTranslation {
    profileType: 'PQ-translation';
    
    extension?: Extension[];
    url: string;
    valueQuantity?: Quantity;
}

