// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Distance } from '../hl7-fhir-r4-core/Distance';
import { Extension } from '../hl7-fhir-r4-core/Extension';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface LocationDistance {
    profileType: 'location-distance';
    
    extension?: Extension[];
    url: string;
    valueDistance?: Distance;
}

