// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from '../hl7-fhir-r4-core/BackboneElement';
import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { Coding } from '../hl7-fhir-r4-core/Coding';
import { DomainResource } from '../hl7-fhir-r4-core/DomainResource';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { MarketingStatus } from '../hl7-fhir-r4-core/MarketingStatus';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { Element } from '../hl7-fhir-r4-core/Element';


export interface MedicinalProductManufacturingBusinessOperation extends BackboneElement {
    authorisationReferenceNumber?: Identifier;
    confidentialityIndicator?: CodeableConcept;
    effectiveDate?: string;
    manufacturer?: Reference<'Organization'>[];
    operationType?: CodeableConcept;
    regulator?: Reference<'Organization'>;
}

export interface MedicinalProductName extends BackboneElement {
    countryLanguage?: MedicinalProductNameCountryLanguage[];
    namePart?: MedicinalProductNameNamePart[];
    productName: string;
}

export interface MedicinalProductNameCountryLanguage extends BackboneElement {
    country: CodeableConcept;
    jurisdiction?: CodeableConcept;
    language: CodeableConcept;
}

export interface MedicinalProductNameNamePart extends BackboneElement {
    part: string;
    type: Coding;
}

export interface MedicinalProductSpecialDesignation extends BackboneElement {
    date?: string;
    identifier?: Identifier[];
    indicationCodeableConcept?: CodeableConcept;
    indicationReference?: Reference<'MedicinalProductIndication'>;
    intendedUse?: CodeableConcept;
    species?: CodeableConcept;
    status?: CodeableConcept;
    type?: CodeableConcept;
}

export interface MedicinalProduct extends DomainResource {
    additionalMonitoringIndicator?: CodeableConcept;
    attachedDocument?: Reference<'DocumentReference'>[];
    clinicalTrial?: Reference<'ResearchStudy'>[];
    combinedPharmaceuticalDoseForm?: CodeableConcept;
    contact?: Reference<'Organization' | 'PractitionerRole'>[];
    crossReference?: Identifier[];
    domain?: Coding;
    identifier?: Identifier[];
    legalStatusOfSupply?: CodeableConcept;
    manufacturingBusinessOperation?: MedicinalProductManufacturingBusinessOperation[];
    marketingStatus?: MarketingStatus[];
    masterFile?: Reference<'DocumentReference'>[];
    name: MedicinalProductName[];
    packagedMedicinalProduct?: Reference<'MedicinalProductPackaged'>[];
    paediatricUseIndicator?: CodeableConcept;
    pharmaceuticalProduct?: Reference<'MedicinalProductPharmaceutical'>[];
    productClassification?: CodeableConcept[];
    specialDesignation?: MedicinalProductSpecialDesignation[];
    specialMeasures?: string[];
    _specialMeasures?: Element;
    type?: CodeableConcept;
}

