// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from '../hl7-fhir-r4-core/BackboneElement';
import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { DomainResource } from '../hl7-fhir-r4-core/DomainResource';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { MarketingStatus } from '../hl7-fhir-r4-core/MarketingStatus';
import { ProdCharacteristic } from '../hl7-fhir-r4-core/ProdCharacteristic';
import { ProductShelfLife } from '../hl7-fhir-r4-core/ProductShelfLife';
import { Quantity } from '../hl7-fhir-r4-core/Quantity';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { Element } from '../hl7-fhir-r4-core/Element';


export interface MedicinalProductPackagedBatchIdentifier extends BackboneElement {
    immediatePackaging?: Identifier;
    outerPackaging: Identifier;
}

export interface MedicinalProductPackagedPackageItem extends BackboneElement {
    alternateMaterial?: CodeableConcept[];
    device?: Reference<'DeviceDefinition'>[];
    identifier?: Identifier[];
    manufacturedItem?: Reference<'MedicinalProductManufactured'>[];
    manufacturer?: Reference<'Organization'>[];
    material?: CodeableConcept[];
    otherCharacteristics?: CodeableConcept[];
    packageItem?: MedicinalProductPackagedPackageItem[];
    physicalCharacteristics?: ProdCharacteristic;
    quantity: Quantity;
    shelfLifeStorage?: ProductShelfLife[];
    type: CodeableConcept;
}

export interface MedicinalProductPackaged extends DomainResource {
    batchIdentifier?: MedicinalProductPackagedBatchIdentifier[];
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    legalStatusOfSupply?: CodeableConcept;
    manufacturer?: Reference<'Organization'>[];
    marketingAuthorization?: Reference<'MedicinalProductAuthorization'>;
    marketingStatus?: MarketingStatus[];
    packageItem: MedicinalProductPackagedPackageItem[];
    subject?: Reference<'MedicinalProduct'>[];
}

