// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Extension } from '../hl7-fhir-r4-core/Extension';
import { Observation } from '../hl7-fhir-r4-core/Observation';
import { ObservationComponent } from '../hl7-fhir-r4-core/Observation';
import { ObservationReferenceRange } from '../hl7-fhir-r4-core/Observation';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface ObservationGenetics {
    profileType: 'Observation-genetics';
    
    extension?: Extension[];
}

