// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from '../hl7-fhir-r4-core/Annotation';
import { EvidenceVariable } from '../hl7-fhir-r4-core/EvidenceVariable';
import { EvidenceVariableCharacteristic } from '../hl7-fhir-r4-core/EvidenceVariable';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface Picoelement {
    __profileUrl: 'http://hl7.org/fhir/StructureDefinition/picoelement';
    
    identifier?: Identifier[];
    title?: string;
    shortTitle?: string;
    date?: string;
    description?: string;
    note?: Annotation[];
    type?: 'dichotomous' | 'continuous' | 'descriptive';
    characteristic: EvidenceVariableCharacteristic[];
}

export const attach_Picoelement = (resource: EvidenceVariable, profile: Picoelement): EvidenceVariable => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/picoelement']
        },
        identifier: profile.identifier,
        title: profile.title,
        shortTitle: profile.shortTitle,
        date: profile.date,
        description: profile.description,
        note: profile.note,
        type: profile.type,
        characteristic: profile.characteristic,
    }
}

export const extract_EvidenceVariable = (resource: EvidenceVariable): Picoelement => {
    return {
        __profileUrl: 'http://hl7.org/fhir/StructureDefinition/picoelement',
        identifier: resource.identifier,
        title: resource.title,
        shortTitle: resource.shortTitle,
        date: resource.date,
        description: resource.description,
        note: resource.note,
        type: resource.type,
        characteristic: resource.characteristic,
    }
}
