// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Extension } from '../hl7-fhir-r4-core/Extension';
import { Timing } from '../hl7-fhir-r4-core/Timing';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface ProcedureSchedule {
    profileType: 'schedule';
    
    extension?: Extension[];
    url: string;
    valueTiming?: Timing;
}

