// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { Extension } from '../hl7-fhir-r4-core/Extension';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface ProcedureProgressStatus {
    profileType: 'progressStatus';
    
    extension?: Extension[];
    url: string;
    valueCodeableConcept?: CodeableConcept;
}

