// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { Provenance } from '../hl7-fhir-r4-core/Provenance';
import { ProvenanceAgent } from '../hl7-fhir-r4-core/Provenance';
import { ProvenanceEntity } from '../hl7-fhir-r4-core/Provenance';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface ProvenanceRelevantHistory {
    __profileUrl: 'http://hl7.org/fhir/StructureDefinition/provenance-relevant-history';
    
    target: Reference<'Resource'>[];
    occurredDateTime?: string;
    reason?: CodeableConcept[];
    activity: CodeableConcept;
    agent: ProvenanceAgent[];
}

export const attach_ProvenanceRelevantHistory = (resource: Provenance, profile: ProvenanceRelevantHistory): Provenance => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/provenance-relevant-history']
        },
        target: profile.target,
        occurredDateTime: profile.occurredDateTime,
        reason: profile.reason,
        activity: profile.activity,
        agent: profile.agent,
    }
}
