// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { Provenance } from '../hl7-fhir-r4-core/Provenance';
import { ProvenanceAgent } from '../hl7-fhir-r4-core/Provenance';
import { ProvenanceEntity } from '../hl7-fhir-r4-core/Provenance';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface ProvenanceRelevantHistory {
    profileType: 'Provenance Relevant History';
    
    target: Reference[];
    occurredDateTime?: string;
    reason?: CodeableConcept[];
    activity: CodeableConcept;
    agent: ProvenanceAgent[];
}

