// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from '../hl7-fhir-r4-core/BackboneElement';
import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { ContactDetail } from '../hl7-fhir-r4-core/ContactDetail';
import { DataRequirement } from '../hl7-fhir-r4-core/DataRequirement';
import { DomainResource } from '../hl7-fhir-r4-core/DomainResource';
import { Duration } from '../hl7-fhir-r4-core/Duration';
import { Expression } from '../hl7-fhir-r4-core/Expression';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { Period } from '../hl7-fhir-r4-core/Period';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { RelatedArtifact } from '../hl7-fhir-r4-core/RelatedArtifact';
import { Timing } from '../hl7-fhir-r4-core/Timing';
import { UsageContext } from '../hl7-fhir-r4-core/UsageContext';
import { Element } from '../hl7-fhir-r4-core/Element';


export interface ResearchElementDefinitionCharacteristic extends BackboneElement {
    definitionCanonical?: string;
    definitionCodeableConcept?: CodeableConcept;
    definitionDataRequirement?: DataRequirement;
    definitionExpression?: Expression;
    exclude?: boolean;
    participantEffectiveDateTime?: string;
    participantEffectiveDescription?: string;
    participantEffectiveDuration?: Duration;
    participantEffectiveGroupMeasure?: 'mean' | 'median' | 'mean-of-mean' | 'mean-of-median' | 'median-of-mean' | 'median-of-median';
    participantEffectivePeriod?: Period;
    participantEffectiveTimeFromStart?: Duration;
    participantEffectiveTiming?: Timing;
    studyEffectiveDateTime?: string;
    studyEffectiveDescription?: string;
    studyEffectiveDuration?: Duration;
    studyEffectiveGroupMeasure?: 'mean' | 'median' | 'mean-of-mean' | 'mean-of-median' | 'median-of-mean' | 'median-of-median';
    studyEffectivePeriod?: Period;
    studyEffectiveTimeFromStart?: Duration;
    studyEffectiveTiming?: Timing;
    unitOfMeasure?: CodeableConcept;
    usageContext?: UsageContext[];
}

export interface ResearchElementDefinition extends DomainResource {
    approvalDate?: string;
    _approvalDate?: Element;
    author?: ContactDetail[];
    characteristic: ResearchElementDefinitionCharacteristic[];
    comment?: string[];
    _comment?: Element;
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    experimental?: boolean;
    _experimental?: Element;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    library?: string[];
    _library?: Element;
    name?: string;
    _name?: Element;
    publisher?: string;
    _publisher?: Element;
    purpose?: string;
    _purpose?: Element;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    shortTitle?: string;
    _shortTitle?: Element;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    subjectCodeableConcept?: CodeableConcept;
    subjectReference?: Reference<'Group'>;
    subtitle?: string;
    _subtitle?: Element;
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    type: 'population' | 'exposure' | 'outcome';
    _type?: Element;
    url?: string;
    _url?: Element;
    usage?: string;
    _usage?: Element;
    useContext?: UsageContext[];
    variableType?: 'dichotomous' | 'continuous' | 'descriptive';
    _variableType?: Element;
    version?: string;
    _version?: Element;
}

