// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { DomainResource } from '../hl7-fhir-r4-core/DomainResource';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface Slot extends DomainResource {
    appointmentType?: CodeableConcept;
    comment?: string;
    _comment?: Element;
    end: string;
    _end?: Element;
    identifier?: Identifier[];
    overbooked?: boolean;
    _overbooked?: Element;
    schedule: Reference<'Schedule'>;
    serviceCategory?: CodeableConcept[];
    serviceType?: CodeableConcept[];
    specialty?: CodeableConcept[];
    start: string;
    _start?: Element;
    status: 'busy' | 'free' | 'busy-unavailable' | 'busy-tentative' | 'entered-in-error';
    _status?: Element;
}

