// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Attachment } from '../hl7-fhir-r4-core/Attachment';
import { BackboneElement } from '../hl7-fhir-r4-core/BackboneElement';
import { CodeableConcept } from '../hl7-fhir-r4-core/CodeableConcept';
import { DomainResource } from '../hl7-fhir-r4-core/DomainResource';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { Element } from '../hl7-fhir-r4-core/Element';


export interface SubstanceProteinSubunit extends BackboneElement {
    cTerminalModification?: string;
    cTerminalModificationId?: Identifier;
    length?: number;
    nTerminalModification?: string;
    nTerminalModificationId?: Identifier;
    sequence?: string;
    sequenceAttachment?: Attachment;
    subunit?: number;
}

export interface SubstanceProtein extends DomainResource {
    disulfideLinkage?: string[];
    _disulfideLinkage?: Element;
    numberOfSubunits?: number;
    _numberOfSubunits?: Element;
    sequenceType?: CodeableConcept;
    subunit?: SubstanceProteinSubunit[];
}

