// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from '../hl7-fhir-r4-core/Annotation';
import { ContactDetail } from '../hl7-fhir-r4-core/ContactDetail';
import { Evidence } from '../hl7-fhir-r4-core/Evidence';
import { Identifier } from '../hl7-fhir-r4-core/Identifier';
import { Reference } from '../hl7-fhir-r4-core/Reference';
import { RelatedArtifact } from '../hl7-fhir-r4-core/RelatedArtifact';
import { Element } from '../hl7-fhir-r4-core/Element';

export interface Synthesis {
    profileType: 'Evidence Synthesis Profile';
    
    description?: string;
    date?: string;
    publisher?: string;
    approvalDate?: string;
    copyright?: string;
    outcome: Reference[];
    title?: string;
    note?: Annotation[];
    author?: ContactDetail[];
    status: string;
    subtitle?: string;
    url?: string;
    identifier?: Identifier[];
    lastReviewDate?: string;
    editor?: ContactDetail[];
    reviewer?: ContactDetail[];
    shortTitle?: string;
    version?: string;
    relatedArtifact?: RelatedArtifact[];
    contact?: ContactDetail[];
    exposureBackground: Reference;
    exposureVariant: Reference[];
}

