// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class ChargeItem : DomainResource
{
    public ResourceReference[]? Service { get; set; }
    public string[]? DefinitionUri { get; set; }
    public ResourceReference? Enterer { get; set; }
    public ResourceReference? RequestingOrganization { get; set; }
    public CodeableConcept? ProductCodeableConcept { get; set; }
    public ResourceReference? ProductReference { get; set; }
    public string[]? DefinitionCanonical { get; set; }
    public CodeableConcept[]? Bodysite { get; set; }
    public Timing? OccurrenceTiming { get; set; }
    public ResourceReference? CostCenter { get; set; }
    public Annotation[]? Note { get; set; }
    public ResourceReference[]? Account { get; set; }
    public CodeableConcept[]? Reason { get; set; }
    public ResourceReference[]? SupportingInformation { get; set; }
    public Period? OccurrencePeriod { get; set; }
    public required ChargeItemStatusEnum Status { get; set; }
    public required CodeableConcept Code { get; set; }
    public Identifier[]? Identifier { get; set; }
    public ResourceReference? Context { get; set; }
    public Quantity? Quantity { get; set; }
    public ResourceReference[]? PartOf { get; set; }
    public Money? PriceOverride { get; set; }
    public string? EnteredDate { get; set; }
    public string? OccurrenceDateTime { get; set; }
    public string? OverrideReason { get; set; }
    public ResourceReference? PerformingOrganization { get; set; }
    public required ResourceReference Subject { get; set; }
    public decimal? FactorOverride { get; set; }
    public ChargeItemPerformer[]? Performer { get; set; }
    
    public class ChargeItemPerformer : BackboneElement
    {
        public CodeableConcept? Function { get; set; }
        public required ResourceReference Actor { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
    
}

