// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class DocumentManifest : DomainResource
{
    public string? Description { get; set; }
    public required ResourceReference[] Content { get; set; }
    public ResourceReference[]? Recipient { get; set; }
    public CodeableConcept? Type { get; set; }
    public string? Created { get; set; }
    public DocumentManifestRelated[]? Related { get; set; }
    public string? Source { get; set; }
    public ResourceReference[]? Author { get; set; }
    public Identifier? MasterIdentifier { get; set; }
    public required StatusEnum Status { get; set; }
    public Identifier[]? Identifier { get; set; }
    public ResourceReference? Subject { get; set; }
    
    public class DocumentManifestRelated : BackboneElement
    {
        public Identifier? Identifier { get; set; }
        public ResourceReference? Ref { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    
    public enum StatusEnum
    {
        Current ,
        Superseded ,
        EnteredDashInDashError ,
    }
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

