// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class ImmunizationRecommendation : DomainResource
{
    public Identifier[]? Identifier { get; set; }
    public required ResourceReference Patient { get; set; }
    public required string Date { get; set; }
    public ResourceReference? Authority { get; set; }
    public required ImmunizationRecommendationRecommendation[] Recommendation { get; set; }
    
    public class ImmunizationRecommendationRecommendation : BackboneElement
    {
        public string? Description { get; set; }
        public long? SeriesDosesPositiveInt { get; set; }
        public CodeableConcept[]? ContraindicatedVaccineCode { get; set; }
        public long? DoseNumberPositiveInt { get; set; }
        public string? Series { get; set; }
        public CodeableConcept[]? VaccineCode { get; set; }
        public string? DoseNumberString { get; set; }
        public string? SeriesDosesString { get; set; }
        public required CodeableConcept ForecastStatus { get; set; }
        public CodeableConcept[]? ForecastReason { get; set; }
        public ImmunizationRecommendationRecommendationDateCriterion[]? DateCriterion { get; set; }
        public CodeableConcept? TargetDisease { get; set; }
        public ResourceReference[]? SupportingImmunization { get; set; }
        public ResourceReference[]? SupportingPatientInformation { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class ImmunizationRecommendationRecommendationDateCriterion : BackboneElement
    {
        public required CodeableConcept Code { get; set; }
        public required string Value { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
    
}

