// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class ImplementationGuide : DomainResource
{
    public string? Description { get; set; }
    public ImplementationGuideDefinition? Definition { get; set; }
    public string? Date { get; set; }
    public string? Publisher { get; set; }
    public required FhirVersionEnum[] FhirVersion { get; set; }
    public LicenseEnum? License { get; set; }
    public CodeableConcept[]? Jurisdiction { get; set; }
    public ImplementationGuideGlobal[]? Global { get; set; }
    public ImplementationGuideDependsOn[]? DependsOn { get; set; }
    public required string Name { get; set; }
    public UsageContext[]? UseContext { get; set; }
    public string? Copyright { get; set; }
    public bool? Experimental { get; set; }
    public ImplementationGuideManifest? Manifest { get; set; }
    public string? Title { get; set; }
    public required StatusEnum Status { get; set; }
    public required string Url { get; set; }
    public string? Version { get; set; }
    public required string PackageId { get; set; }
    public ContactDetail[]? Contact { get; set; }
    
    public class ImplementationGuideDefinition : BackboneElement
    {
        public ImplementationGuideDefinitionGrouping[]? Grouping { get; set; }
        public required ImplementationGuideDefinitionResource[] Resource { get; set; }
        public ImplementationGuideDefinitionPage? Page { get; set; }
        public ImplementationGuideDefinitionParameter[]? Parameter { get; set; }
        public ImplementationGuideDefinitionTemplate[]? Template { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideDefinitionGrouping : BackboneElement
    {
        public required string Name { get; set; }
        public string? Description { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideDefinitionPage : BackboneElement
    {
        public string? NameUrl { get; set; }
        public ResourceReference? NameReference { get; set; }
        public required string Title { get; set; }
        public required GenerationEnum Generation { get; set; }
        public ImplementationGuideDefinitionPage[]? Page { get; set; }
        
        public enum GenerationEnum
        {
            Html ,
            Markdown ,
            Xml ,
            Generated ,
        }
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideDefinitionParameter : BackboneElement
    {
        public required CodeEnum Code { get; set; }
        public required string Value { get; set; }
        
        public enum CodeEnum
        {
            Apply ,
            PathDashResource ,
            PathDashPages ,
            PathDashTxDashCache ,
            ExpansionDashParameter ,
            RuleDashBrokenDashLinks ,
            GenerateDashXml ,
            GenerateDashJson ,
            GenerateDashTurtle ,
            HtmlDashTemplate ,
        }
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideDefinitionResource : BackboneElement
    {
        public required ResourceReference Reference { get; set; }
        public FhirVersionEnum[]? FhirVersion { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public bool? ExampleBoolean { get; set; }
        public string? ExampleCanonical { get; set; }
        public string? GroupingId { get; set; }
        
        public enum FhirVersionEnum
        {
            _0Dot01 ,
            _0Dot05 ,
            _0Dot06 ,
            _0Dot11 ,
            _0Dot0Dot80 ,
            _0Dot0Dot81 ,
            _0Dot0Dot82 ,
            _0Dot4Dot0 ,
            _0Dot5Dot0 ,
            _1Dot0Dot0 ,
            _1Dot0Dot1 ,
            _1Dot0Dot2 ,
            _1Dot1Dot0 ,
            _1Dot4Dot0 ,
            _1Dot6Dot0 ,
            _1Dot8Dot0 ,
            _3Dot0Dot0 ,
            _3Dot0Dot1 ,
            _3Dot3Dot0 ,
            _3Dot5Dot0 ,
            _4Dot0Dot0 ,
            _4Dot0Dot1 ,
        }
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideDefinitionTemplate : BackboneElement
    {
        public required string Code { get; set; }
        public required string Source { get; set; }
        public string? Scope { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideDependsOn : BackboneElement
    {
        public required string Uri { get; set; }
        public string? PackageId { get; set; }
        public string? Version { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideGlobal : BackboneElement
    {
        public required TypeEnum Type { get; set; }
        public required string Profile { get; set; }
        
        public enum TypeEnum
        {
            Account ,
            ActivityDefinition ,
            AdverseEvent ,
            AllergyIntolerance ,
            Appointment ,
            AppointmentResponse ,
            AuditEvent ,
            Basic ,
            Binary ,
            BiologicallyDerivedProduct ,
            BodyStructure ,
            Bundle ,
            CapabilityStatement ,
            CarePlan ,
            CareTeam ,
            CatalogEntry ,
            ChargeItem ,
            ChargeItemDefinition ,
            Claim ,
            ClaimResponse ,
            ClinicalImpression ,
            CodeSystem ,
            Communication ,
            CommunicationRequest ,
            CompartmentDefinition ,
            Composition ,
            ConceptMap ,
            Condition ,
            Consent ,
            Contract ,
            Coverage ,
            CoverageEligibilityRequest ,
            CoverageEligibilityResponse ,
            DetectedIssue ,
            Device ,
            DeviceDefinition ,
            DeviceMetric ,
            DeviceRequest ,
            DeviceUseStatement ,
            DiagnosticReport ,
            DocumentManifest ,
            DocumentReference ,
            DomainResource ,
            EffectEvidenceSynthesis ,
            Encounter ,
            Endpoint ,
            EnrollmentRequest ,
            EnrollmentResponse ,
            EpisodeOfCare ,
            EventDefinition ,
            Evidence ,
            EvidenceVariable ,
            ExampleScenario ,
            ExplanationOfBenefit ,
            FamilyMemberHistory ,
            Flag ,
            Goal ,
            GraphDefinition ,
            Group ,
            GuidanceResponse ,
            HealthcareService ,
            ImagingStudy ,
            Immunization ,
            ImmunizationEvaluation ,
            ImmunizationRecommendation ,
            ImplementationGuide ,
            InsurancePlan ,
            Invoice ,
            Library ,
            Linkage ,
            List ,
            Location ,
            Measure ,
            MeasureReport ,
            Media ,
            Medication ,
            MedicationAdministration ,
            MedicationDispense ,
            MedicationKnowledge ,
            MedicationRequest ,
            MedicationStatement ,
            MedicinalProduct ,
            MedicinalProductAuthorization ,
            MedicinalProductContraindication ,
            MedicinalProductIndication ,
            MedicinalProductIngredient ,
            MedicinalProductInteraction ,
            MedicinalProductManufactured ,
            MedicinalProductPackaged ,
            MedicinalProductPharmaceutical ,
            MedicinalProductUndesirableEffect ,
            MessageDefinition ,
            MessageHeader ,
            MolecularSequence ,
            NamingSystem ,
            NutritionOrder ,
            Observation ,
            ObservationDefinition ,
            OperationDefinition ,
            OperationOutcome ,
            Organization ,
            OrganizationAffiliation ,
            Parameters ,
            Patient ,
            PaymentNotice ,
            PaymentReconciliation ,
            Person ,
            PlanDefinition ,
            Practitioner ,
            PractitionerRole ,
            Procedure ,
            Provenance ,
            Questionnaire ,
            QuestionnaireResponse ,
            RelatedPerson ,
            RequestGroup ,
            ResearchDefinition ,
            ResearchElementDefinition ,
            ResearchStudy ,
            ResearchSubject ,
            Resource ,
            RiskAssessment ,
            RiskEvidenceSynthesis ,
            Schedule ,
            SearchParameter ,
            ServiceRequest ,
            Slot ,
            Specimen ,
            SpecimenDefinition ,
            StructureDefinition ,
            StructureMap ,
            Subscription ,
            Substance ,
            SubstanceNucleicAcid ,
            SubstancePolymer ,
            SubstanceProtein ,
            SubstanceReferenceInformation ,
            SubstanceSourceMaterial ,
            SubstanceSpecification ,
            SupplyDelivery ,
            SupplyRequest ,
            Task ,
            TerminologyCapabilities ,
            TestReport ,
            TestScript ,
            ValueSet ,
            VerificationResult ,
            VisionPrescription ,
        }
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideManifest : BackboneElement
    {
        public string? Rendering { get; set; }
        public required ImplementationGuideManifestResource[] Resource { get; set; }
        public ImplementationGuideManifestPage[]? Page { get; set; }
        public string[]? Image { get; set; }
        public string[]? Other { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideManifestPage : BackboneElement
    {
        public required string Name { get; set; }
        public string? Title { get; set; }
        public string[]? Anchor { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class ImplementationGuideManifestResource : BackboneElement
    {
        public required ResourceReference Reference { get; set; }
        public bool? ExampleBoolean { get; set; }
        public string? ExampleCanonical { get; set; }
        public string? RelativePath { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    
    public enum FhirVersionEnum
    {
        _0Dot01 ,
        _0Dot05 ,
        _0Dot06 ,
        _0Dot11 ,
        _0Dot0Dot80 ,
        _0Dot0Dot81 ,
        _0Dot0Dot82 ,
        _0Dot4Dot0 ,
        _0Dot5Dot0 ,
        _1Dot0Dot0 ,
        _1Dot0Dot1 ,
        _1Dot0Dot2 ,
        _1Dot1Dot0 ,
        _1Dot4Dot0 ,
        _1Dot6Dot0 ,
        _1Dot8Dot0 ,
        _3Dot0Dot0 ,
        _3Dot0Dot1 ,
        _3Dot3Dot0 ,
        _3Dot5Dot0 ,
        _4Dot0Dot0 ,
        _4Dot0Dot1 ,
    }
    public enum LicenseEnum
    {
        NotDashOpenDashSource ,
        _0BSD ,
        AAL ,
        Abstyles ,
        AdobeDash2006 ,
        AdobeDashGlyph ,
        ADSL ,
        AFLDash1Dot1 ,
        AFLDash1Dot2 ,
        AFLDash2Dot0 ,
        AFLDash2Dot1 ,
        AFLDash3Dot0 ,
        Afmparse ,
        AGPLDash1Dot0DashOnly ,
        AGPLDash1Dot0DashOrDashLater ,
        AGPLDash3Dot0DashOnly ,
        AGPLDash3Dot0DashOrDashLater ,
        Aladdin ,
        AMDPLPA ,
        AML ,
        AMPAS ,
        ANTLRDashPD ,
        ApacheDash1Dot0 ,
        ApacheDash1Dot1 ,
        ApacheDash2Dot0 ,
        APAFML ,
        APLDash1Dot0 ,
        APSLDash1Dot0 ,
        APSLDash1Dot1 ,
        APSLDash1Dot2 ,
        APSLDash2Dot0 ,
        ArtisticDash1Dot0DashCl8 ,
        ArtisticDash1Dot0DashPerl ,
        ArtisticDash1Dot0 ,
        ArtisticDash2Dot0 ,
        Bahyph ,
        Barr ,
        Beerware ,
        BitTorrentDash1Dot0 ,
        BitTorrentDash1Dot1 ,
        Borceux ,
        BSDDash1DashClause ,
        BSDDash2DashClauseDashFreeBSD ,
        BSDDash2DashClauseDashNetBSD ,
        BSDDash2DashClauseDashPatent ,
        BSDDash2DashClause ,
        BSDDash3DashClauseDashAttribution ,
        BSDDash3DashClauseDashClear ,
        BSDDash3DashClauseDashLBNL ,
        BSDDash3DashClauseDashNoDashNuclearDashLicenseDash2014 ,
        BSDDash3DashClauseDashNoDashNuclearDashLicense ,
        BSDDash3DashClauseDashNoDashNuclearDashWarranty ,
        BSDDash3DashClause ,
        BSDDash4DashClauseDashUC ,
        BSDDash4DashClause ,
        BSDDashProtection ,
        BSDDashSourceDashCode ,
        BSLDash1Dot0 ,
        Bzip2Dash1Dot0Dot5 ,
        Bzip2Dash1Dot0Dot6 ,
        Caldera ,
        CATOSLDash1Dot1 ,
        CCDashBYDash1Dot0 ,
        CCDashBYDash2Dot0 ,
        CCDashBYDash2Dot5 ,
        CCDashBYDash3Dot0 ,
        CCDashBYDash4Dot0 ,
        CCDashBYDashNCDash1Dot0 ,
        CCDashBYDashNCDash2Dot0 ,
        CCDashBYDashNCDash2Dot5 ,
        CCDashBYDashNCDash3Dot0 ,
        CCDashBYDashNCDash4Dot0 ,
        CCDashBYDashNCDashNDDash1Dot0 ,
        CCDashBYDashNCDashNDDash2Dot0 ,
        CCDashBYDashNCDashNDDash2Dot5 ,
        CCDashBYDashNCDashNDDash3Dot0 ,
        CCDashBYDashNCDashNDDash4Dot0 ,
        CCDashBYDashNCDashSADash1Dot0 ,
        CCDashBYDashNCDashSADash2Dot0 ,
        CCDashBYDashNCDashSADash2Dot5 ,
        CCDashBYDashNCDashSADash3Dot0 ,
        CCDashBYDashNCDashSADash4Dot0 ,
        CCDashBYDashNDDash1Dot0 ,
        CCDashBYDashNDDash2Dot0 ,
        CCDashBYDashNDDash2Dot5 ,
        CCDashBYDashNDDash3Dot0 ,
        CCDashBYDashNDDash4Dot0 ,
        CCDashBYDashSADash1Dot0 ,
        CCDashBYDashSADash2Dot0 ,
        CCDashBYDashSADash2Dot5 ,
        CCDashBYDashSADash3Dot0 ,
        CCDashBYDashSADash4Dot0 ,
        CC0Dash1Dot0 ,
        CDDLDash1Dot0 ,
        CDDLDash1Dot1 ,
        CDLADashPermissiveDash1Dot0 ,
        CDLADashSharingDash1Dot0 ,
        CECILLDash1Dot0 ,
        CECILLDash1Dot1 ,
        CECILLDash2Dot0 ,
        CECILLDash2Dot1 ,
        CECILLDashB ,
        CECILLDashC ,
        ClArtistic ,
        CNRIDashJython ,
        CNRIDashPythonDashGPLDashCompatible ,
        CNRIDashPython ,
        CondorDash1Dot1 ,
        CPALDash1Dot0 ,
        CPLDash1Dot0 ,
        CPOLDash1Dot02 ,
        Crossword ,
        CrystalStacker ,
        CUADashOPLDash1Dot0 ,
        Cube ,
        Curl ,
        DDashFSLDash1Dot0 ,
        Diffmark ,
        DOC ,
        Dotseqn ,
        DSDP ,
        Dvipdfm ,
        ECLDash1Dot0 ,
        ECLDash2Dot0 ,
        EFLDash1Dot0 ,
        EFLDash2Dot0 ,
        EGenix ,
        Entessa ,
        EPLDash1Dot0 ,
        EPLDash2Dot0 ,
        ErlPLDash1Dot1 ,
        EUDatagrid ,
        EUPLDash1Dot0 ,
        EUPLDash1Dot1 ,
        EUPLDash1Dot2 ,
        Eurosym ,
        Fair ,
        FrameworxDash1Dot0 ,
        FreeImage ,
        FSFAP ,
        FSFUL ,
        FSFULLR ,
        FTL ,
        GFDLDash1Dot1DashOnly ,
        GFDLDash1Dot1DashOrDashLater ,
        GFDLDash1Dot2DashOnly ,
        GFDLDash1Dot2DashOrDashLater ,
        GFDLDash1Dot3DashOnly ,
        GFDLDash1Dot3DashOrDashLater ,
        Giftware ,
        GL2PS ,
        Glide ,
        Glulxe ,
        Gnuplot ,
        GPLDash1Dot0DashOnly ,
        GPLDash1Dot0DashOrDashLater ,
        GPLDash2Dot0DashOnly ,
        GPLDash2Dot0DashOrDashLater ,
        GPLDash3Dot0DashOnly ,
        GPLDash3Dot0DashOrDashLater ,
        GSOAPDash1Dot3b ,
        HaskellReport ,
        HPND ,
        IBMDashPibs ,
        ICU ,
        IJG ,
        ImageMagick ,
        IMatix ,
        Imlib2 ,
        InfoDashZIP ,
        IntelDashACPI ,
        Intel ,
        InterbaseDash1Dot0 ,
        IPA ,
        IPLDash1Dot0 ,
        ISC ,
        JasPerDash2Dot0 ,
        JSON ,
        LALDash1Dot2 ,
        LALDash1Dot3 ,
        Latex2e ,
        Leptonica ,
        LGPLDash2Dot0DashOnly ,
        LGPLDash2Dot0DashOrDashLater ,
        LGPLDash2Dot1DashOnly ,
        LGPLDash2Dot1DashOrDashLater ,
        LGPLDash3Dot0DashOnly ,
        LGPLDash3Dot0DashOrDashLater ,
        LGPLLR ,
        Libpng ,
        Libtiff ,
        LiLiQDashPDash1Dot1 ,
        LiLiQDashRDash1Dot1 ,
        LiLiQDashRplusDash1Dot1 ,
        LinuxDashOpenIB ,
        LPLDash1Dot0 ,
        LPLDash1Dot02 ,
        LPPLDash1Dot0 ,
        LPPLDash1Dot1 ,
        LPPLDash1Dot2 ,
        LPPLDash1Dot3a ,
        LPPLDash1Dot3c ,
        MakeIndex ,
        MirOS ,
        MITDash0 ,
        MITDashAdvertising ,
        MITDashCMU ,
        MITDashEnna ,
        MITDashFeh ,
        MIT ,
        MITNFA ,
        Motosoto ,
        Mpich2 ,
        MPLDash1Dot0 ,
        MPLDash1Dot1 ,
        MPLDash2Dot0DashNoDashCopyleftDashException ,
        MPLDash2Dot0 ,
        MSDashPL ,
        MSDashRL ,
        MTLL ,
        Multics ,
        Mup ,
        NASADash1Dot3 ,
        Naumen ,
        NBPLDash1Dot0 ,
        NCSA ,
        NetDashSNMP ,
        NetCDF ,
        Newsletr ,
        NGPL ,
        NLODDash1Dot0 ,
        NLPL ,
        Nokia ,
        NOSL ,
        Noweb ,
        NPLDash1Dot0 ,
        NPLDash1Dot1 ,
        NPOSLDash3Dot0 ,
        NRL ,
        NTP ,
        OCCTDashPL ,
        OCLCDash2Dot0 ,
        ODbLDash1Dot0 ,
        OFLDash1Dot0 ,
        OFLDash1Dot1 ,
        OGTSL ,
        OLDAPDash1Dot1 ,
        OLDAPDash1Dot2 ,
        OLDAPDash1Dot3 ,
        OLDAPDash1Dot4 ,
        OLDAPDash2Dot0Dot1 ,
        OLDAPDash2Dot0 ,
        OLDAPDash2Dot1 ,
        OLDAPDash2Dot2Dot1 ,
        OLDAPDash2Dot2Dot2 ,
        OLDAPDash2Dot2 ,
        OLDAPDash2Dot3 ,
        OLDAPDash2Dot4 ,
        OLDAPDash2Dot5 ,
        OLDAPDash2Dot6 ,
        OLDAPDash2Dot7 ,
        OLDAPDash2Dot8 ,
        OML ,
        OpenSSL ,
        OPLDash1Dot0 ,
        OSETDashPLDash2Dot1 ,
        OSLDash1Dot0 ,
        OSLDash1Dot1 ,
        OSLDash2Dot0 ,
        OSLDash2Dot1 ,
        OSLDash3Dot0 ,
        PDDLDash1Dot0 ,
        PHPDash3Dot0 ,
        PHPDash3Dot01 ,
        Plexus ,
        PostgreSQL ,
        Psfrag ,
        Psutils ,
        PythonDash2Dot0 ,
        Qhull ,
        QPLDash1Dot0 ,
        Rdisc ,
        RHeCosDash1Dot1 ,
        RPLDash1Dot1 ,
        RPLDash1Dot5 ,
        RPSLDash1Dot0 ,
        RSADashMD ,
        RSCPL ,
        Ruby ,
        SAXDashPD ,
        Saxpath ,
        SCEA ,
        Sendmail ,
        SGIDashBDash1Dot0 ,
        SGIDashBDash1Dot1 ,
        SGIDashBDash2Dot0 ,
        SimPLDash2Dot0 ,
        SISSLDash1Dot2 ,
        SISSL ,
        Sleepycat ,
        SMLNJ ,
        SMPPL ,
        SNIA ,
        SpencerDash86 ,
        SpencerDash94 ,
        SpencerDash99 ,
        SPLDash1Dot0 ,
        SugarCRMDash1Dot1Dot3 ,
        SWL ,
        TCL ,
        TCPDashWrappers ,
        TMate ,
        TORQUEDash1Dot1 ,
        TOSL ,
        UnicodeDashDFSDash2015 ,
        UnicodeDashDFSDash2016 ,
        UnicodeDashTOU ,
        Unlicense ,
        UPLDash1Dot0 ,
        Vim ,
        VOSTROM ,
        VSLDash1Dot0 ,
        W3CDash19980720 ,
        W3CDash20150513 ,
        W3C ,
        WatcomDash1Dot0 ,
        Wsuipa ,
        WTFPL ,
        X11 ,
        Xerox ,
        XFree86Dash1Dot1 ,
        Xinetd ,
        Xnet ,
        Xpp ,
        XSkat ,
        YPLDash1Dot0 ,
        YPLDash1Dot1 ,
        Zed ,
        ZendDash2Dot0 ,
        ZimbraDash1Dot3 ,
        ZimbraDash1Dot4 ,
        ZlibDashAcknowledgement ,
        Zlib ,
        ZPLDash1Dot1 ,
        ZPLDash2Dot0 ,
        ZPLDash2Dot1 ,
    }
    public enum StatusEnum
    {
        Draft ,
        Active ,
        Retired ,
        Unknown ,
    }
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

