// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class Linkage : DomainResource
{
    public bool? Active { get; set; }
    public ResourceReference? Author { get; set; }
    public required LinkageItem[] Item { get; set; }
    
    public class LinkageItem : BackboneElement
    {
        public required LinkageTypeEnum Type { get; set; }
        public required ResourceReference Resource { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
    
}

