// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class OperationDefinition : DomainResource
{
    public string? Description { get; set; }
    public string? Date { get; set; }
    public required bool System { get; set; }
    public string? Publisher { get; set; }
    public required bool Instance { get; set; }
    public CodeableConcept[]? Jurisdiction { get; set; }
    public string? Purpose { get; set; }
    public required string Name { get; set; }
    public UsageContext[]? UseContext { get; set; }
    public required bool Type { get; set; }
    public OperationDefinitionOverload[]? Overload { get; set; }
    public bool? Experimental { get; set; }
    public string? OutputProfile { get; set; }
    public string? Title { get; set; }
    public required string Status { get; set; }
    public string[]? Resource { get; set; }
    public bool? AffectsState { get; set; }
    public required string Kind { get; set; }
    public string? Comment { get; set; }
    public string? Url { get; set; }
    public required string Code { get; set; }
    public string? Base { get; set; }
    public string? Version { get; set; }
    public ContactDetail[]? Contact { get; set; }
    public string? InputProfile { get; set; }
    public OperationDefinitionParameter[]? Parameter { get; set; }
    
    public class OperationDefinitionOverload : BackboneElement
    {
        public string[]? ParameterName { get; set; }
        public string? Comment { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class OperationDefinitionParameter : BackboneElement
    {
        public required int Min { get; set; }
        public string? SearchType { get; set; }
        public required string Use { get; set; }
        public required string Name { get; set; }
        public OperationDefinitionParameter[]? Part { get; set; }
        public string? Type { get; set; }
        public OperationDefinitionParameterReferencedFrom[]? ReferencedFrom { get; set; }
        public string? Documentation { get; set; }
        public OperationDefinitionParameterBinding? Binding { get; set; }
        public required string Max { get; set; }
        public string[]? TargetProfile { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class OperationDefinitionParameterBinding : BackboneElement
    {
        public required string Strength { get; set; }
        public required string ValueSet { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class OperationDefinitionParameterReferencedFrom : BackboneElement
    {
        public required string Source { get; set; }
        public string? SourceId { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

