// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class OrganizationAffiliation : DomainResource
{
    public CodeableConcept[]? Specialty { get; set; }
    public ResourceReference? Organization { get; set; }
    public ResourceReference? ParticipatingOrganization { get; set; }
    public bool? Active { get; set; }
    public CodeableConcept[]? Code { get; set; }
    public Identifier[]? Identifier { get; set; }
    public ContactPoint[]? Telecom { get; set; }
    public ResourceReference[]? Network { get; set; }
    public Period? Period { get; set; }
    public ResourceReference[]? Location { get; set; }
    public ResourceReference[]? Endpoint { get; set; }
    public ResourceReference[]? HealthcareService { get; set; }
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

