// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class PaymentReconciliation : DomainResource
{
    public ResourceReference? Requestor { get; set; }
    public ResourceReference? Request { get; set; }
    public required Money PaymentAmount { get; set; }
    public PaymentReconciliationProcessNote[]? ProcessNote { get; set; }
    public required string Created { get; set; }
    public RemittanceOutcomeEnum? Outcome { get; set; }
    public string? Disposition { get; set; }
    public Identifier? PaymentIdentifier { get; set; }
    public required PaymentReconciliationStatusEnum Status { get; set; }
    public required string PaymentDate { get; set; }
    public Identifier[]? Identifier { get; set; }
    public Period? Period { get; set; }
    public ResourceReference? PaymentIssuer { get; set; }
    public CodeableConcept? FormCode { get; set; }
    public PaymentReconciliationDetail[]? Detail { get; set; }
    
    public class PaymentReconciliationDetail : BackboneElement
    {
        public ResourceReference? Response { get; set; }
        public Money? Amount { get; set; }
        public string? Date { get; set; }
        public ResourceReference? Request { get; set; }
        public required CodeableConcept Type { get; set; }
        public ResourceReference? Responsible { get; set; }
        public ResourceReference? Payee { get; set; }
        public Identifier? Predecessor { get; set; }
        public Identifier? Identifier { get; set; }
        public ResourceReference? Submitter { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class PaymentReconciliationProcessNote : BackboneElement
    {
        public NoteTypeEnum? Type { get; set; }
        public string? Text { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
    
}

