// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class SubstanceProtein : DomainResource
{
    public CodeableConcept? SequenceType { get; set; }
    public int? NumberOfSubunits { get; set; }
    public string[]? DisulfideLinkage { get; set; }
    public SubstanceProteinSubunit[]? Subunit { get; set; }
    
    public class SubstanceProteinSubunit : BackboneElement
    {
        public int? Subunit { get; set; }
        public string? Sequence { get; set; }
        public int? Length { get; set; }
        public Attachment? SequenceAttachment { get; set; }
        public Identifier? NTerminalModificationId { get; set; }
        public string? NTerminalModification { get; set; }
        public Identifier? CTerminalModificationId { get; set; }
        public string? CTerminalModification { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

