// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class Subscription : DomainResource
{
    public required SubscriptionStatusEnum Status { get; set; }
    public ContactPoint[]? Contact { get; set; }
    public string? End { get; set; }
    public required string Reason { get; set; }
    public required string Criteria { get; set; }
    public string? Error { get; set; }
    public required SubscriptionChannel Channel { get; set; }
    
    public class SubscriptionChannel : BackboneElement
    {
        public required SubscriptionChannelTypeEnum Type { get; set; }
        public string? Endpoint { get; set; }
        public string? Payload { get; set; }
        public string[]? Header { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
    
}

