// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class Substance : DomainResource
{
    public Identifier[]? Identifier { get; set; }
    public StatusEnum? Status { get; set; }
    public CodeableConcept[]? Category { get; set; }
    public required CodeableConcept Code { get; set; }
    public string? Description { get; set; }
    public SubstanceInstance[]? Instance { get; set; }
    public SubstanceIngredient[]? Ingredient { get; set; }
    
    public class SubstanceIngredient : BackboneElement
    {
        public Ratio? Quantity { get; set; }
        public CodeableConcept? SubstanceCodeableConcept { get; set; }
        public ResourceReference? SubstanceReference { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    public class SubstanceInstance : BackboneElement
    {
        public Identifier? Identifier { get; set; }
        public string? Expiry { get; set; }
        public Quantity? Quantity { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
        
    }
    
    
    public enum StatusEnum
    {
        Active ,
        Inactive ,
        EnteredDashInDashError ,
    }
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

