// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace Aidbox.FHIR.R4.Core;

public class TestScript : DomainResource
{
    public string? Description { get; set; }
    public string? Date { get; set; }
    public TestScriptVariable[]? Variable { get; set; }
    public string? Publisher { get; set; }
    public CodeableConcept[]? Jurisdiction { get; set; }
    public string? Purpose { get; set; }
    public required string Name { get; set; }
    public UsageContext[]? UseContext { get; set; }
    public string? Copyright { get; set; }
    public bool? Experimental { get; set; }
    public string? Title { get; set; }
    public TestScriptSetup? Setup { get; set; }
    public required PublicationStatusEnum Status { get; set; }
    public required string Url { get; set; }
    public Identifier? Identifier { get; set; }
    public TestScriptOrigin[]? Origin { get; set; }
    public TestScriptFixture[]? Fixture { get; set; }
    public string? Version { get; set; }
    public TestScriptTeardown? Teardown { get; set; }
    public ContactDetail[]? Contact { get; set; }
    public TestScriptMetadata? Metadata { get; set; }
    public TestScriptDestination[]? Destination { get; set; }
    public TestScriptTest[]? Test { get; set; }
    public ResourceReference[]? Profile { get; set; }
    
    public class TestScriptDestination : BackboneElement
    {
        public required int Index { get; set; }
        public required Coding Profile { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptFixture : BackboneElement
    {
        public required bool Autocreate { get; set; }
        public required bool Autodelete { get; set; }
        public ResourceReference? Resource { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptMetadata : BackboneElement
    {
        public TestScriptMetadataLink[]? Link { get; set; }
        public required TestScriptMetadataCapability[] Capability { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptMetadataCapability : BackboneElement
    {
        public required bool Required { get; set; }
        public required bool Validated { get; set; }
        public string? Description { get; set; }
        public int[]? Origin { get; set; }
        public int? Destination { get; set; }
        public string[]? Link { get; set; }
        public required string Capabilities { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptMetadataLink : BackboneElement
    {
        public required string Url { get; set; }
        public string? Description { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptOrigin : BackboneElement
    {
        public required int Index { get; set; }
        public required Coding Profile { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptSetup : BackboneElement
    {
        public required TestScriptSetupAction[] Action { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptSetupAction : BackboneElement
    {
        public TestScriptSetupActionOperation? Operation { get; set; }
        public TestScriptSetupActionAssert? Assert { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptSetupActionAssert : BackboneElement
    {
        public AssertionResponseTypesEnum? Response { get; set; }
        public string? Description { get; set; }
        public string? Path { get; set; }
        public string? HeaderField { get; set; }
        public string? CompareToSourceId { get; set; }
        public string? Expression { get; set; }
        public string? Value { get; set; }
        public required bool WarningOnly { get; set; }
        public string? CompareToSourceExpression { get; set; }
        public string? Label { get; set; }
        public FhirdefinedTypeEnum? Resource { get; set; }
        public string? ResponseCode { get; set; }
        public string? MinimumId { get; set; }
        public AssertionOperatorTypeEnum? Operator { get; set; }
        public string? ContentType { get; set; }
        public string? CompareToSourcePath { get; set; }
        public string? ValidateProfileId { get; set; }
        public string? SourceId { get; set; }
        public TestScriptRequestMethodCodeEnum? RequestMethod { get; set; }
        public string? RequestURL { get; set; }
        public AssertionDirectionTypeEnum? Direction { get; set; }
        public bool? NavigationLinks { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptSetupActionOperation : BackboneElement
    {
        public string? Description { get; set; }
        public TestScriptRequestMethodCodeEnum? Method { get; set; }
        public string? TargetId { get; set; }
        public TestScriptSetupActionOperationRequestHeader[]? RequestHeader { get; set; }
        public string? Params { get; set; }
        public Coding? Type { get; set; }
        public string? RequestId { get; set; }
        public required bool EncodeRequestUrl { get; set; }
        public string? Label { get; set; }
        public FhirdefinedTypeEnum? Resource { get; set; }
        public string? Url { get; set; }
        public int? Origin { get; set; }
        public string? ContentType { get; set; }
        public string? SourceId { get; set; }
        public string? ResponseId { get; set; }
        public int? Destination { get; set; }
        public string? Accept { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptSetupActionOperationRequestHeader : BackboneElement
    {
        public required string Field { get; set; }
        public required string Value { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptTeardown : BackboneElement
    {
        public required TestScriptTeardownAction[] Action { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptTeardownAction : BackboneElement
    {
        public required TestScriptSetupActionOperation Operation { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptTest : BackboneElement
    {
        public string? Name { get; set; }
        public string? Description { get; set; }
        public required TestScriptTestAction[] Action { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptTestAction : BackboneElement
    {
        public TestScriptSetupActionOperation? Operation { get; set; }
        public TestScriptSetupActionAssert? Assert { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    public class TestScriptVariable : BackboneElement
    {
        public required string Name { get; set; }
        public string? DefaultValue { get; set; }
        public string? Description { get; set; }
        public string? Expression { get; set; }
        public string? HeaderField { get; set; }
        public string? Hint { get; set; }
        public string? Path { get; set; }
        public string? SourceId { get; set; }
        
        public override string ToString() => 
            JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
        
    }
    
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Config.JsonSerializerOptions);
    
}

