import path from 'path';

import { Generator, GeneratorOptions } from '../../generator';
import { ClassField, TypeSchema } from '../../typeschema';
import { groupedByPackage, kebabCase, pascalCase, removeConstraints } from '../../utils';

// Naming conventions
// directory naming: kebab-case
// file naming: PascalCase for only-class files, kebab-case for other files
// function naming: camelCase
// class naming: PascalCase

interface TypeScriptGeneratorOptions extends GeneratorOptions {
    // tabSize: 2
}

const typeMap = {
    boolean: 'boolean',
    instant: 'string',
    time: 'string',
    date: 'string',
    dateTime: 'string',

    decimal: 'number',
    integer: 'number',
    unsignedInt: 'number',
    positiveInt: 'number',
    integer64: 'number',
    base64Binary: 'string',

    uri: 'string',
    url: 'string',
    canonical: 'string',
    oid: 'string',
    uuid: 'string',

    string: 'string',
    code: 'string',
    markdown: 'string',
    id: 'string',
    xhtml: 'string',
};

// prettier-ignore
const keywords = new Set([
    'abstract', 'any', 'as', 'async', 'await', 'boolean', 'bigint', 'break', 
    'case', 'catch', 'class', 'const', 'constructor', 'continue', 'debugger', 
    'declare', 'default', 'delete', 'do', 'else', 'enum', 'export', 'extends', 
    'extern', 'false', 'finally', 'for', 'function', 'from', 'get', 'goto', 'if', 
    'implements', 'import', 'in', 'infer', 'instanceof', 'interface', 'keyof', 
    'let', 'module', 'namespace', 'never', 'new', 'null', 'number', 'object', 
    'of', 'override', 'private', 'protected', 'public', 'readonly', 'return', 
    'satisfies', 'set', 'static', 'string', 'super', 'switch', 'this', 'throw', 
    'true', 'try', 'type', 'typeof', 'unknown', 'var', 'void', 'while',
]);

const canonicalToName = (canonical: string | undefined) => {
    if (!canonical) return undefined;
    return canonical.split('/').pop();
};

function uppercaseFirstLetter(str: string): string {
    if (!str || str.length === 0) return str;
    return str.charAt(0).toUpperCase() + str.slice(1);
}

function uppercaseFirstLetterOfEach(strings: string[]): string[] {
    return strings.map((str) => uppercaseFirstLetter(str));
}

const deriveTheSchemaName = (schema: TypeSchema) => {
    if (schema.type.base === 'http://hl7.org/fhir/StructureDefinition/BackboneElement') {
        const [canonical, ...path] = schema?.path || [];
        return [canonicalToName(canonical), ...uppercaseFirstLetterOfEach(path)].join('');
    }

    return schema.type.name;
};

class TypeScriptGenerator extends Generator {
    constructor(opts: TypeScriptGeneratorOptions) {
        super({
            ...opts,
            typeMap,
            keywords,
            staticDir: path.resolve(__dirname, 'static'),
        });
    }

    generateDependenciesImports(schema: TypeSchema) {
        if (schema.dependencies) {
            const deps = schema.dependencies
                .filter((dep) => dep.kind === 'complex-type' || dep.kind === 'resource')
                .sort((a, b) => a.name.localeCompare(b.name));

            for (const dep of deps) {
                this.lineSM(`import { ${dep.name} } from './${dep.name}'`);
            }
        }
    }

    generateDisclaimer() {
        this.line('// WARNING: This file is autogenerated by FHIR Schema Codegen.');
        this.line('// https://github.com/fhir-schema/fhir-schema-codegen');
        this.line('// Any manual changes made to this file may be overwritten.');
    }

    generateNestedTypes(schema: TypeSchema) {
        if (schema.nestedTypes) {
            this.line('// Nested Types');
            this.line();
            for (let subtype of schema.nestedTypes) {
                this.generateType(subtype);
            }
        }
    }

    addFieldExtension(fieldName: string, field: ClassField): void {
        if (field.type.kind === 'primitive-type') {
            this.lineSM(`_${fieldName}?: Element`);
        }
    }

    addResourceTypeField(schema: TypeSchema): void {
        this.lineSM(`resourceType: '${schema.type.name}'`);
    }

    generateType(schema: TypeSchema) {
        const name = deriveTheSchemaName(schema);
        const parent = canonicalToName(schema.type.base);
        const extendsClause = parent && `extends ${parent}`;

        this.curlyBlock(['export', 'interface', name, extendsClause], () => {
            if (!schema.fields) {
                return;
            }

            // we have to provide utility field name called resourceType
            if (schema.type.kind === 'resource') {
                // this.addResourceTypeField(schema);
            }

            const fields = Object.entries(schema.fields).sort((a, b) => a[0].localeCompare(b[0]));

            for (const [fieldName, field] of fields) {
                if ('elementReference' in field) continue; // recursive type
                if ('choices' in field) continue; // polymorphic type
                if ('path' in field) continue; // backbone element type

                const type = this.getFieldType(field);
                const fieldNameFixed = this.getFieldName(fieldName);
                const optionalSymbol = field.required ? '' : '?';
                const arraySymbol = field.array ? '[]' : '';

                this.lineSM(`${fieldNameFixed}${optionalSymbol}:`, `${type}${arraySymbol}`);

                if (schema.type.kind === 'resource' || schema.type.kind === 'complex-type') {
                    this.addFieldExtension(fieldName, field);
                }
            }
        });

        this.line();
    }

    generateResourceModule(schema: TypeSchema) {
        this.file(pascalCase(schema.type.name) + '.ts', () => {
            this.generateDisclaimer();
            this.line();

            this.generateDependenciesImports(schema);
            this.line();

            this.generateNestedTypes(schema);

            this.line('// Resource Type');
            this.generateType(schema);
        });
    }

    generateIndexFile(schemas: TypeSchema[]) {
        this.file('index.ts', () => {
            const names = schemas.map((schema) => schema.type.name);

            names.forEach((n) => this.lineSM(`import { ${n} } from './${n}'`));
            this.lineSM(`export { ${names.join(', ')} }`);

            this.curlyBlock(['export type ResourceTypeMap = '], () => {
                this.lineSM('User: Record<string, any>');
                names.forEach((name) => this.lineSM(`${name}: ${name}`));
            });
            this.lineSM('export type ResourceType = keyof ResourceTypeMap');

            this.squareBlock(['export const resourceList: readonly ResourceType[] = '], () => {
                names.forEach((n) => this.line(`'${n}', `));
            });
        });
    }

    generate() {
        this.copyStaticFiles();

        this.dir('types', async () => {
            const typesToGenerate = removeConstraints([...this.loader.complexTypes(), ...this.loader.resources()]);
            const groupedComplexTypes = groupedByPackage(typesToGenerate);

            for (const [packageName, packageSchemas] of Object.entries(groupedComplexTypes)) {
                this.dir(path.join('types', kebabCase(packageName)), () => {
                    this.generateIndexFile(packageSchemas);

                    for (const schema of packageSchemas) {
                        this.generateResourceModule(schema);
                    }
                });
            }
        });
    }
}

export { TypeScriptGenerator };
export { type TypeScriptGeneratorOptions };

export function createGenerator(options: TypeScriptGeneratorOptions) {
    return new TypeScriptGenerator(options);
}
