# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class AppointmentParticipant(BackboneElement):
    actor: Optional[Reference] = None
    period: Optional[Period] = None
    required: Optional[Literal["required", "optional", "information-only"]] = None
    status: Optional[Literal["accepted", "declined", "tentative", "needs-action"]] = None
    type: Optional[L[CodeableConcept]] = None


class Appointment(DomainResource):
    appointment_type: Optional[CodeableConcept] = None
    based_on: Optional[L[Reference]] = None
    cancelation_reason: Optional[CodeableConcept] = None
    comment: Optional[str] = None
    created: Optional[str] = None
    description: Optional[str] = None
    end: Optional[str] = None
    identifier: Optional[L[Identifier]] = None
    minutes_duration: Optional[PositiveInt] = None
    participant: Optional[L[AppointmentParticipant]] = None
    patient_instruction: Optional[str] = None
    priority: Optional[int] = None
    reason_code: Optional[L[CodeableConcept]] = None
    reason_reference: Optional[L[Reference]] = None
    requested_period: Optional[L[Period]] = None
    service_category: Optional[L[CodeableConcept]] = None
    service_type: Optional[L[CodeableConcept]] = None
    slot: Optional[L[Reference]] = None
    specialty: Optional[L[CodeableConcept]] = None
    start: Optional[str] = None
    status: Optional[Literal["proposed", "pending", "booked", "arrived", "fulfilled", "cancelled", "noshow", "entered-in-error", "checked-in", "waitlist"]] = None
    supporting_information: Optional[L[Reference]] = None

