# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import Optional, List as L, Literal, ForwardRef

from aidbox.hl7_fhir_r4_core.base import CodeableConcept, Identifier, Reference
from aidbox.hl7_fhir_r4_core.domain_resource import DomainResource
from aidbox.hl7_fhir_r4_core.resource_families import DomainResourceFamily


class Basic(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Basic',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Basic'
    )
    
    author: Optional[Reference] = Field(None, alias="author", serialization_alias="author")
    code: Optional[CodeableConcept] = Field(None, alias="code", serialization_alias="code")
    created: Optional[str] = Field(None, alias="created", serialization_alias="created")
    identifier: Optional[L[Identifier]] = Field(None, alias="identifier", serialization_alias="identifier")
    subject: Optional[Reference] = Field(None, alias="subject", serialization_alias="subject")

