# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class BiologicallyDerivedProductProcessing(BackboneElement):
    additive: Optional[Reference] = None
    description: Optional[str] = None
    procedure: Optional[CodeableConcept] = None
    time_date_time: Optional[str] = None
    time_period: Optional[Period] = None

class BiologicallyDerivedProductStorage(BackboneElement):
    description: Optional[str] = None
    duration: Optional[Period] = None
    scale: Optional[Literal["farenheit", "celsius", "kelvin"]] = None
    temperature: Optional[float] = None

class BiologicallyDerivedProductManipulation(BackboneElement):
    description: Optional[str] = None
    time_date_time: Optional[str] = None
    time_period: Optional[Period] = None

class BiologicallyDerivedProductCollection(BackboneElement):
    collected_date_time: Optional[str] = None
    collected_period: Optional[Period] = None
    collector: Optional[Reference] = None
    source: Optional[Reference] = None


class BiologicallyDerivedProduct(DomainResource):
    collection: Optional[BiologicallyDerivedProductCollection] = None
    identifier: Optional[L[Identifier]] = None
    manipulation: Optional[BiologicallyDerivedProductManipulation] = None
    parent: Optional[L[Reference]] = None
    processing: Optional[L[BiologicallyDerivedProductProcessing]] = None
    product_category: Optional[Literal["organ", "tissue", "fluid", "cells", "biologicalAgent"]] = None
    product_code: Optional[CodeableConcept] = None
    quantity: Optional[int] = None
    request: Optional[L[Reference]] = None
    status: Optional[Literal["available", "unavailable"]] = None
    storage: Optional[L[BiologicallyDerivedProductStorage]] = None

