# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import Optional, List as L, Literal, ForwardRef

from aidbox.hl7_fhir_r4_core.base import Attachment, CodeableConcept, Identifier, Reference
from aidbox.hl7_fhir_r4_core.domain_resource import DomainResource
from aidbox.hl7_fhir_r4_core.resource_families import DomainResourceFamily


class BodyStructure(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='BodyStructure',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='BodyStructure'
    )
    
    active: Optional[bool] = Field(None, alias="active", serialization_alias="active")
    description: Optional[str] = Field(None, alias="description", serialization_alias="description")
    identifier: Optional[L[Identifier]] = Field(None, alias="identifier", serialization_alias="identifier")
    image: Optional[L[Attachment]] = Field(None, alias="image", serialization_alias="image")
    location: Optional[CodeableConcept] = Field(None, alias="location", serialization_alias="location")
    location_qualifier: Optional[L[CodeableConcept]] = Field(None, alias="locationQualifier", serialization_alias="locationQualifier")
    morphology: Optional[CodeableConcept] = Field(None, alias="morphology", serialization_alias="morphology")
    patient: Optional[Reference] = Field(None, alias="patient", serialization_alias="patient")

