# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class BodyStructure(DomainResource):
    active: Optional[bool] = None
    description: Optional[str] = None
    identifier: Optional[L[Identifier]] = None
    image: Optional[L[Attachment]] = None
    location: Optional[CodeableConcept] = None
    location_qualifier: Optional[L[CodeableConcept]] = None
    morphology: Optional[CodeableConcept] = None
    patient: Optional[Reference] = None

