# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class ChargeItemDefinitionPropertyGroupPriceComponent(BackboneElement):
    amount: Optional[Money] = None
    code: Optional[CodeableConcept] = None
    factor: Optional[float] = None
    type: Optional[Literal["base", "surcharge", "deduction", "discount", "tax", "informational"]] = None

class ChargeItemDefinitionPropertyGroup(BackboneElement):
    applicability: Optional[L[ChargeItemDefinitionApplicability]] = None
    price_component: Optional[L[ChargeItemDefinitionPropertyGroupPriceComponent]] = None

class ChargeItemDefinitionApplicability(BackboneElement):
    description: Optional[str] = None
    expression: Optional[str] = None
    language: Optional[str] = None


class ChargeItemDefinition(DomainResource):
    applicability: Optional[L[ChargeItemDefinitionApplicability]] = None
    approval_date: Optional[str] = None
    code: Optional[CodeableConcept] = None
    contact: Optional[L[ContactDetail]] = None
    copyright: Optional[str] = None
    date: Optional[str] = None
    derived_from_uri: Optional[L[str]] = None
    description: Optional[str] = None
    effective_period: Optional[Period] = None
    experimental: Optional[bool] = None
    identifier: Optional[L[Identifier]] = None
    instance: Optional[L[Reference]] = None
    jurisdiction: Optional[L[CodeableConcept]] = None
    last_review_date: Optional[str] = None
    part_of: Optional[L[str]] = None
    property_group: Optional[L[ChargeItemDefinitionPropertyGroup]] = None
    publisher: Optional[str] = None
    replaces: Optional[L[str]] = None
    status: Optional[Literal["draft", "active", "retired", "unknown"]] = None
    title: Optional[str] = None
    url: Optional[str] = None
    use_context: Optional[L[UsageContext]] = None
    version: Optional[str] = None

