# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class ClinicalImpressionInvestigation(BackboneElement):
    code: Optional[CodeableConcept] = None
    item: Optional[L[Reference]] = None

class ClinicalImpressionFinding(BackboneElement):
    basis: Optional[str] = None
    item_codeable_concept: Optional[CodeableConcept] = None
    item_reference: Optional[Reference] = None


class ClinicalImpression(DomainResource):
    assessor: Optional[Reference] = None
    code: Optional[CodeableConcept] = None
    date: Optional[str] = None
    description: Optional[str] = None
    effective_date_time: Optional[str] = None
    effective_period: Optional[Period] = None
    encounter: Optional[Reference] = None
    finding: Optional[L[ClinicalImpressionFinding]] = None
    identifier: Optional[L[Identifier]] = None
    investigation: Optional[L[ClinicalImpressionInvestigation]] = None
    note: Optional[L[Annotation]] = None
    previous: Optional[Reference] = None
    problem: Optional[L[Reference]] = None
    prognosis_codeable_concept: Optional[L[CodeableConcept]] = None
    prognosis_reference: Optional[L[Reference]] = None
    protocol: Optional[L[str]] = None
    status: Optional[Literal["in-progress", "completed", "entered-in-error", "preparation", "in-progress", "not-done", "on-hold", "stopped", "completed", "entered-in-error", "unknown"]] = None
    status_reason: Optional[CodeableConcept] = None
    subject: Optional[Reference] = None
    summary: Optional[str] = None
    supporting_info: Optional[L[Reference]] = None

