# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class CodeSystemProperty(BackboneElement):
    code: Optional[str] = None
    description: Optional[str] = None
    type: Optional[Literal["code", "Coding", "string", "integer", "boolean", "dateTime", "decimal"]] = None
    uri: Optional[str] = None

class CodeSystemFilter(BackboneElement):
    code: Optional[str] = None
    description: Optional[str] = None
    operator: Optional[L[Literal["=", "is-a", "descendent-of", "is-not-a", "regex", "in", "not-in", "generalizes", "exists"]]] = None
    value: Optional[str] = None

class CodeSystemConceptDesignation(BackboneElement):
    language: Optional[str] = None
    use: Optional[Coding] = None
    value: Optional[str] = None

class CodeSystemConceptProperty(BackboneElement):
    code: Optional[str] = None
    value_boolean: Optional[bool] = None
    value_code: Optional[str] = None
    value_coding: Optional[Coding] = None
    value_date_time: Optional[str] = None
    value_decimal: Optional[float] = None
    value_integer: Optional[int] = None
    value_string: Optional[str] = None

class CodeSystemConcept(BackboneElement):
    code: Optional[str] = None
    concept: Optional[L[CodeSystemConcept]] = None
    definition: Optional[str] = None
    designation: Optional[L[CodeSystemConceptDesignation]] = None
    display: Optional[str] = None
    property: Optional[L[CodeSystemConceptProperty]] = None


class CodeSystem(DomainResource):
    case_sensitive: Optional[bool] = None
    compositional: Optional[bool] = None
    concept: Optional[L[CodeSystemConcept]] = None
    contact: Optional[L[ContactDetail]] = None
    content: Optional[Literal["not-present", "example", "fragment", "complete", "supplement"]] = None
    copyright: Optional[str] = None
    count: Optional[int] = None
    date: Optional[str] = None
    description: Optional[str] = None
    experimental: Optional[bool] = None
    filter: Optional[L[CodeSystemFilter]] = None
    hierarchy_meaning: Optional[Literal["grouped-by", "is-a", "part-of", "classified-with"]] = None
    identifier: Optional[L[Identifier]] = None
    jurisdiction: Optional[L[CodeableConcept]] = None
    name: Optional[str] = None
    property: Optional[L[CodeSystemProperty]] = None
    publisher: Optional[str] = None
    purpose: Optional[str] = None
    status: Optional[Literal["draft", "active", "retired", "unknown"]] = None
    supplements: Optional[str] = None
    title: Optional[str] = None
    url: Optional[str] = None
    use_context: Optional[L[UsageContext]] = None
    value_set: Optional[str] = None
    version: Optional[str] = None
    version_needed: Optional[bool] = None

