# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import Optional, List as L, Literal, ForwardRef

from aidbox.hl7_fhir_r4_core.base import Attachment, BackboneElement, CodeableConcept, Coding, Identifier, Period, Reference
from aidbox.hl7_fhir_r4_core.domain_resource import DomainResource
from aidbox.hl7_fhir_r4_core.resource_families import DomainResourceFamily


class ConsentProvisionActor(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    reference: Optional[Reference] = Field(None, alias="reference", serialization_alias="reference")
    role: Optional[CodeableConcept] = Field(None, alias="role", serialization_alias="role")

class ConsentProvisionData(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    meaning: Optional[Literal["instance", "related", "dependents", "authoredby"]] = Field(None, alias="meaning", serialization_alias="meaning")
    reference: Optional[Reference] = Field(None, alias="reference", serialization_alias="reference")

class ConsentProvision(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: Optional[L[CodeableConcept]] = Field(None, alias="action", serialization_alias="action")
    actor: Optional[L[ConsentProvisionActor]] = Field(None, alias="actor", serialization_alias="actor")
    class_: Optional[L[Coding]] = Field(None, alias="class", serialization_alias="class")
    code: Optional[L[CodeableConcept]] = Field(None, alias="code", serialization_alias="code")
    data: Optional[L[ConsentProvisionData]] = Field(None, alias="data", serialization_alias="data")
    data_period: Optional[Period] = Field(None, alias="dataPeriod", serialization_alias="dataPeriod")
    period: Optional[Period] = Field(None, alias="period", serialization_alias="period")
    provision: Optional[L[ConsentProvision]] = Field(None, alias="provision", serialization_alias="provision")
    purpose: Optional[L[Coding]] = Field(None, alias="purpose", serialization_alias="purpose")
    security_label: Optional[L[Coding]] = Field(None, alias="securityLabel", serialization_alias="securityLabel")
    type: Optional[Literal["deny", "permit"]] = Field(None, alias="type", serialization_alias="type")

class ConsentVerification(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    verification_date: Optional[str] = Field(None, alias="verificationDate", serialization_alias="verificationDate")
    verified: Optional[bool] = Field(None, alias="verified", serialization_alias="verified")
    verified_with: Optional[Reference] = Field(None, alias="verifiedWith", serialization_alias="verifiedWith")

class ConsentPolicy(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    authority: Optional[str] = Field(None, alias="authority", serialization_alias="authority")
    uri: Optional[str] = Field(None, alias="uri", serialization_alias="uri")


class Consent(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Consent',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Consent'
    )
    
    category: Optional[L[CodeableConcept]] = Field(None, alias="category", serialization_alias="category")
    date_time: Optional[str] = Field(None, alias="dateTime", serialization_alias="dateTime")
    identifier: Optional[L[Identifier]] = Field(None, alias="identifier", serialization_alias="identifier")
    organization: Optional[L[Reference]] = Field(None, alias="organization", serialization_alias="organization")
    patient: Optional[Reference] = Field(None, alias="patient", serialization_alias="patient")
    performer: Optional[L[Reference]] = Field(None, alias="performer", serialization_alias="performer")
    policy: Optional[L[ConsentPolicy]] = Field(None, alias="policy", serialization_alias="policy")
    policy_rule: Optional[CodeableConcept] = Field(None, alias="policyRule", serialization_alias="policyRule")
    provision: Optional[ConsentProvision] = Field(None, alias="provision", serialization_alias="provision")
    scope: Optional[CodeableConcept] = Field(None, alias="scope", serialization_alias="scope")
    source_attachment: Optional[Attachment] = Field(None, alias="sourceAttachment", serialization_alias="sourceAttachment")
    source_reference: Optional[Reference] = Field(None, alias="sourceReference", serialization_alias="sourceReference")
    status: Optional[Literal["draft", "proposed", "active", "rejected", "inactive", "entered-in-error"]] = Field(None, alias="status", serialization_alias="status")
    verification: Optional[L[ConsentVerification]] = Field(None, alias="verification", serialization_alias="verification")

