# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class CoverageEligibilityResponseInsuranceItemBenefit(BackboneElement):
    allowed_money: Optional[Money] = None
    allowed_string: Optional[str] = None
    allowed_unsigned_int: Optional[int] = None
    type: Optional[CodeableConcept] = None
    used_money: Optional[Money] = None
    used_string: Optional[str] = None
    used_unsigned_int: Optional[int] = None

class CoverageEligibilityResponseInsuranceItem(BackboneElement):
    authorization_required: Optional[bool] = None
    authorization_supporting: Optional[L[CodeableConcept]] = None
    authorization_url: Optional[str] = None
    benefit: Optional[L[CoverageEligibilityResponseInsuranceItemBenefit]] = None
    category: Optional[CodeableConcept] = None
    description: Optional[str] = None
    excluded: Optional[bool] = None
    modifier: Optional[L[CodeableConcept]] = None
    name: Optional[str] = None
    network: Optional[CodeableConcept] = None
    product_or_service: Optional[CodeableConcept] = None
    provider: Optional[Reference] = None
    term: Optional[CodeableConcept] = None
    unit: Optional[CodeableConcept] = None

class CoverageEligibilityResponseInsurance(BackboneElement):
    benefit_period: Optional[Period] = None
    coverage: Optional[Reference] = None
    inforce: Optional[bool] = None
    item: Optional[L[CoverageEligibilityResponseInsuranceItem]] = None

class CoverageEligibilityResponseError(BackboneElement):
    code: Optional[CodeableConcept] = None


class CoverageEligibilityResponse(DomainResource):
    created: Optional[str] = None
    disposition: Optional[str] = None
    error: Optional[L[CoverageEligibilityResponseError]] = None
    form: Optional[CodeableConcept] = None
    identifier: Optional[L[Identifier]] = None
    insurance: Optional[L[CoverageEligibilityResponseInsurance]] = None
    insurer: Optional[Reference] = None
    outcome: Optional[Literal["queued", "complete", "error", "partial"]] = None
    patient: Optional[Reference] = None
    pre_auth_ref: Optional[str] = None
    purpose: Optional[L[Literal["auth-requirements", "benefits", "discovery", "validation"]]] = None
    request: Optional[Reference] = None
    requestor: Optional[Reference] = None
    serviced_date: Optional[str] = None
    serviced_period: Optional[Period] = None
    status: Optional[Literal["active", "cancelled", "draft", "entered-in-error"]] = None

