# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class DeviceDefinitionDeviceName(BackboneElement):
    name: Optional[str] = None
    type: Optional[Literal["udi-label-name", "user-friendly-name", "patient-reported-name", "manufacturer-name", "model-name", "other"]] = None

class DeviceDefinitionProperty(BackboneElement):
    type: Optional[CodeableConcept] = None
    value_code: Optional[L[CodeableConcept]] = None
    value_quantity: Optional[L[Quantity]] = None

class DeviceDefinitionUdiDeviceIdentifier(BackboneElement):
    device_identifier: Optional[str] = None
    issuer: Optional[str] = None
    jurisdiction: Optional[str] = None

class DeviceDefinitionCapability(BackboneElement):
    description: Optional[L[CodeableConcept]] = None
    type: Optional[CodeableConcept] = None

class DeviceDefinitionSpecialization(BackboneElement):
    system_type: Optional[str] = None
    version: Optional[str] = None

class DeviceDefinitionMaterial(BackboneElement):
    allergenic_indicator: Optional[bool] = None
    alternate: Optional[bool] = None
    substance: Optional[CodeableConcept] = None


class DeviceDefinition(DomainResource):
    capability: Optional[L[DeviceDefinitionCapability]] = None
    contact: Optional[L[ContactPoint]] = None
    device_name: Optional[L[DeviceDefinitionDeviceName]] = None
    identifier: Optional[L[Identifier]] = None
    language_code: Optional[L[CodeableConcept]] = None
    manufacturer_reference: Optional[Reference] = None
    manufacturer_string: Optional[str] = None
    material: Optional[L[DeviceDefinitionMaterial]] = None
    model_number: Optional[str] = None
    note: Optional[L[Annotation]] = None
    online_information: Optional[str] = None
    owner: Optional[Reference] = None
    parent_device: Optional[Reference] = None
    physical_characteristics: Optional[ProdCharacteristic] = None
    property: Optional[L[DeviceDefinitionProperty]] = None
    quantity: Optional[Quantity] = None
    safety: Optional[L[CodeableConcept]] = None
    shelf_life_storage: Optional[L[ProductShelfLife]] = None
    specialization: Optional[L[DeviceDefinitionSpecialization]] = None
    type: Optional[CodeableConcept] = None
    udi_device_identifier: Optional[L[DeviceDefinitionUdiDeviceIdentifier]] = None
    url: Optional[str] = None
    version: Optional[L[str]] = None

