# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class EvidenceVariableCharacteristic(BackboneElement):
    definition_canonical: Optional[str] = None
    definition_codeable_concept: Optional[CodeableConcept] = None
    definition_data_requirement: Optional[DataRequirement] = None
    definition_expression: Optional[Expression] = None
    definition_reference: Optional[Reference] = None
    definition_trigger_definition: Optional[TriggerDefinition] = None
    description: Optional[str] = None
    exclude: Optional[bool] = None
    group_measure: Optional[Literal["mean", "median", "mean-of-mean", "mean-of-median", "median-of-mean", "median-of-median"]] = None
    participant_effective_date_time: Optional[str] = None
    participant_effective_duration: Optional[Duration] = None
    participant_effective_period: Optional[Period] = None
    participant_effective_timing: Optional[Timing] = None
    time_from_start: Optional[Duration] = None
    usage_context: Optional[L[UsageContext]] = None


class EvidenceVariable(DomainResource):
    approval_date: Optional[str] = None
    author: Optional[L[ContactDetail]] = None
    characteristic: Optional[L[EvidenceVariableCharacteristic]] = None
    contact: Optional[L[ContactDetail]] = None
    copyright: Optional[str] = None
    date: Optional[str] = None
    description: Optional[str] = None
    editor: Optional[L[ContactDetail]] = None
    effective_period: Optional[Period] = None
    endorser: Optional[L[ContactDetail]] = None
    identifier: Optional[L[Identifier]] = None
    jurisdiction: Optional[L[CodeableConcept]] = None
    last_review_date: Optional[str] = None
    name: Optional[str] = None
    note: Optional[L[Annotation]] = None
    publisher: Optional[str] = None
    related_artifact: Optional[L[RelatedArtifact]] = None
    reviewer: Optional[L[ContactDetail]] = None
    short_title: Optional[str] = None
    status: Optional[Literal["draft", "active", "retired", "unknown"]] = None
    subtitle: Optional[str] = None
    title: Optional[str] = None
    topic: Optional[L[CodeableConcept]] = None
    type: Optional[Literal["dichotomous", "continuous", "descriptive"]] = None
    url: Optional[str] = None
    use_context: Optional[L[UsageContext]] = None
    version: Optional[str] = None

