# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class GroupMember(BackboneElement):
    entity: Optional[Reference] = None
    inactive: Optional[bool] = None
    period: Optional[Period] = None

class GroupCharacteristic(BackboneElement):
    code: Optional[CodeableConcept] = None
    exclude: Optional[bool] = None
    period: Optional[Period] = None
    value_boolean: Optional[bool] = None
    value_codeable_concept: Optional[CodeableConcept] = None
    value_quantity: Optional[Quantity] = None
    value_range: Optional[Range] = None
    value_reference: Optional[Reference] = None


class Group(DomainResource):
    active: Optional[bool] = None
    actual: Optional[bool] = None
    characteristic: Optional[L[GroupCharacteristic]] = None
    code: Optional[CodeableConcept] = None
    identifier: Optional[L[Identifier]] = None
    managing_entity: Optional[Reference] = None
    member: Optional[L[GroupMember]] = None
    name: Optional[str] = None
    quantity: Optional[int] = None
    type: Optional[Literal["person", "animal", "practitioner", "device", "medication", "substance"]] = None

