# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import Optional, List as L, Literal

from aidbox.hl7_fhir_r4_core.base import Annotation, BackboneElement, CodeableConcept, Identifier, Reference
from aidbox.hl7_fhir_r4_core.domain_resource import DomainResource


class ListEntry(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    date: Optional[str] = Field(None, alias="date", serialization_alias="date")
    deleted: Optional[bool] = Field(None, alias="deleted", serialization_alias="deleted")
    flag: Optional[CodeableConcept] = Field(None, alias="flag", serialization_alias="flag")
    item: Optional[Reference] = Field(None, alias="item", serialization_alias="item")


class List(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='List',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='List'
    )
    
    code: Optional[CodeableConcept] = Field(None, alias="code", serialization_alias="code")
    date: Optional[str] = Field(None, alias="date", serialization_alias="date")
    empty_reason: Optional[CodeableConcept] = Field(None, alias="emptyReason", serialization_alias="emptyReason")
    encounter: Optional[Reference] = Field(None, alias="encounter", serialization_alias="encounter")
    entry: Optional[L[ListEntry]] = Field(None, alias="entry", serialization_alias="entry")
    identifier: Optional[L[Identifier]] = Field(None, alias="identifier", serialization_alias="identifier")
    mode: Optional[Literal["working", "snapshot", "changes"]] = Field(None, alias="mode", serialization_alias="mode")
    note: Optional[L[Annotation]] = Field(None, alias="note", serialization_alias="note")
    ordered_by: Optional[CodeableConcept] = Field(None, alias="orderedBy", serialization_alias="orderedBy")
    source: Optional[Reference] = Field(None, alias="source", serialization_alias="source")
    status: Optional[Literal["current", "retired", "entered-in-error"]] = Field(None, alias="status", serialization_alias="status")
    subject: Optional[Reference] = Field(None, alias="subject", serialization_alias="subject")
    title: Optional[str] = Field(None, alias="title", serialization_alias="title")

