# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class MeasureReportGroupPopulation(BackboneElement):
    code: Optional[CodeableConcept] = None
    count: Optional[int] = None
    subject_results: Optional[Reference] = None

class MeasureReportGroupStratifierStratumComponent(BackboneElement):
    code: Optional[CodeableConcept] = None
    value: Optional[CodeableConcept] = None

class MeasureReportGroupStratifierStratumPopulation(BackboneElement):
    code: Optional[CodeableConcept] = None
    count: Optional[int] = None
    subject_results: Optional[Reference] = None

class MeasureReportGroupStratifierStratum(BackboneElement):
    component: Optional[L[MeasureReportGroupStratifierStratumComponent]] = None
    measure_score: Optional[Quantity] = None
    population: Optional[L[MeasureReportGroupStratifierStratumPopulation]] = None
    value: Optional[CodeableConcept] = None

class MeasureReportGroupStratifier(BackboneElement):
    code: Optional[L[CodeableConcept]] = None
    stratum: Optional[L[MeasureReportGroupStratifierStratum]] = None

class MeasureReportGroup(BackboneElement):
    code: Optional[CodeableConcept] = None
    measure_score: Optional[Quantity] = None
    population: Optional[L[MeasureReportGroupPopulation]] = None
    stratifier: Optional[L[MeasureReportGroupStratifier]] = None


class MeasureReport(DomainResource):
    date: Optional[str] = None
    evaluated_resource: Optional[L[Reference]] = None
    group: Optional[L[MeasureReportGroup]] = None
    identifier: Optional[L[Identifier]] = None
    improvement_notation: Optional[CodeableConcept] = None
    measure: Optional[str] = None
    period: Optional[Period] = None
    reporter: Optional[Reference] = None
    status: Optional[Literal["complete", "pending", "error"]] = None
    subject: Optional[Reference] = None
    type: Optional[Literal["individual", "subject-list", "summary", "data-collection"]] = None

