# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class MeasureGroupPopulation(BackboneElement):
    code: Optional[CodeableConcept] = None
    criteria: Optional[Expression] = None
    description: Optional[str] = None

class MeasureGroupStratifierComponent(BackboneElement):
    code: Optional[CodeableConcept] = None
    criteria: Optional[Expression] = None
    description: Optional[str] = None

class MeasureGroupStratifier(BackboneElement):
    code: Optional[CodeableConcept] = None
    component: Optional[L[MeasureGroupStratifierComponent]] = None
    criteria: Optional[Expression] = None
    description: Optional[str] = None

class MeasureGroup(BackboneElement):
    code: Optional[CodeableConcept] = None
    description: Optional[str] = None
    population: Optional[L[MeasureGroupPopulation]] = None
    stratifier: Optional[L[MeasureGroupStratifier]] = None

class MeasureSupplementalData(BackboneElement):
    code: Optional[CodeableConcept] = None
    criteria: Optional[Expression] = None
    description: Optional[str] = None
    usage: Optional[L[CodeableConcept]] = None


class Measure(DomainResource):
    approval_date: Optional[str] = None
    author: Optional[L[ContactDetail]] = None
    clinical_recommendation_statement: Optional[str] = None
    composite_scoring: Optional[CodeableConcept] = None
    contact: Optional[L[ContactDetail]] = None
    copyright: Optional[str] = None
    date: Optional[str] = None
    definition: Optional[L[str]] = None
    description: Optional[str] = None
    disclaimer: Optional[str] = None
    editor: Optional[L[ContactDetail]] = None
    effective_period: Optional[Period] = None
    endorser: Optional[L[ContactDetail]] = None
    experimental: Optional[bool] = None
    group: Optional[L[MeasureGroup]] = None
    guidance: Optional[str] = None
    identifier: Optional[L[Identifier]] = None
    improvement_notation: Optional[CodeableConcept] = None
    jurisdiction: Optional[L[CodeableConcept]] = None
    last_review_date: Optional[str] = None
    library: Optional[L[str]] = None
    name: Optional[str] = None
    publisher: Optional[str] = None
    purpose: Optional[str] = None
    rate_aggregation: Optional[str] = None
    rationale: Optional[str] = None
    related_artifact: Optional[L[RelatedArtifact]] = None
    reviewer: Optional[L[ContactDetail]] = None
    risk_adjustment: Optional[str] = None
    scoring: Optional[CodeableConcept] = None
    status: Optional[Literal["draft", "active", "retired", "unknown"]] = None
    subject_codeable_concept: Optional[CodeableConcept] = None
    subject_reference: Optional[Reference] = None
    subtitle: Optional[str] = None
    supplemental_data: Optional[L[MeasureSupplementalData]] = None
    title: Optional[str] = None
    topic: Optional[L[CodeableConcept]] = None
    type: Optional[L[CodeableConcept]] = None
    url: Optional[str] = None
    usage: Optional[str] = None
    use_context: Optional[L[UsageContext]] = None
    version: Optional[str] = None

