# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class MedicationRequestSubstitution(BackboneElement):
    allowed_boolean: Optional[bool] = None
    allowed_codeable_concept: Optional[CodeableConcept] = None
    reason: Optional[CodeableConcept] = None

class MedicationRequestDispenseRequestInitialFill(BackboneElement):
    duration: Optional[Duration] = None
    quantity: Optional[Quantity] = None

class MedicationRequestDispenseRequest(BackboneElement):
    dispense_interval: Optional[Duration] = None
    expected_supply_duration: Optional[Duration] = None
    initial_fill: Optional[MedicationRequestDispenseRequestInitialFill] = None
    number_of_repeats_allowed: Optional[int] = None
    performer: Optional[Reference] = None
    quantity: Optional[Quantity] = None
    validity_period: Optional[Period] = None


class MedicationRequest(DomainResource):
    authored_on: Optional[str] = None
    based_on: Optional[L[Reference]] = None
    category: Optional[L[CodeableConcept]] = None
    course_of_therapy_type: Optional[CodeableConcept] = None
    detected_issue: Optional[L[Reference]] = None
    dispense_request: Optional[MedicationRequestDispenseRequest] = None
    do_not_perform: Optional[bool] = None
    dosage_instruction: Optional[L[Dosage]] = None
    encounter: Optional[Reference] = None
    event_history: Optional[L[Reference]] = None
    group_identifier: Optional[Identifier] = None
    identifier: Optional[L[Identifier]] = None
    instantiates_canonical: Optional[L[str]] = None
    instantiates_uri: Optional[L[str]] = None
    insurance: Optional[L[Reference]] = None
    intent: Optional[Literal["proposal", "plan", "order", "original-order", "reflex-order", "filler-order", "instance-order", "option"]] = None
    medication_codeable_concept: Optional[CodeableConcept] = None
    medication_reference: Optional[Reference] = None
    note: Optional[L[Annotation]] = None
    performer: Optional[Reference] = None
    performer_type: Optional[CodeableConcept] = None
    priority: Optional[Literal["routine", "urgent", "asap", "stat"]] = None
    prior_prescription: Optional[Reference] = None
    reason_code: Optional[L[CodeableConcept]] = None
    reason_reference: Optional[L[Reference]] = None
    recorder: Optional[Reference] = None
    reported_boolean: Optional[bool] = None
    reported_reference: Optional[Reference] = None
    requester: Optional[Reference] = None
    status: Optional[Literal["active", "on-hold", "cancelled", "completed", "entered-in-error", "stopped", "draft", "unknown"]] = None
    status_reason: Optional[CodeableConcept] = None
    subject: Optional[Reference] = None
    substitution: Optional[MedicationRequestSubstitution] = None
    supporting_information: Optional[L[Reference]] = None

