# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class MedicationAdministrationDosage(BackboneElement):
    dose: Optional[Quantity] = None
    method: Optional[CodeableConcept] = None
    rate_quantity: Optional[Quantity] = None
    rate_ratio: Optional[Ratio] = None
    route: Optional[CodeableConcept] = None
    site: Optional[CodeableConcept] = None
    text: Optional[str] = None

class MedicationAdministrationPerformer(BackboneElement):
    actor: Optional[Reference] = None
    function: Optional[CodeableConcept] = None


class MedicationAdministration(DomainResource):
    category: Optional[CodeableConcept] = None
    context: Optional[Reference] = None
    device: Optional[L[Reference]] = None
    dosage: Optional[MedicationAdministrationDosage] = None
    effective_date_time: Optional[str] = None
    effective_period: Optional[Period] = None
    event_history: Optional[L[Reference]] = None
    identifier: Optional[L[Identifier]] = None
    instantiates: Optional[L[str]] = None
    medication_codeable_concept: Optional[CodeableConcept] = None
    medication_reference: Optional[Reference] = None
    note: Optional[L[Annotation]] = None
    part_of: Optional[L[Reference]] = None
    performer: Optional[L[MedicationAdministrationPerformer]] = None
    reason_code: Optional[L[CodeableConcept]] = None
    reason_reference: Optional[L[Reference]] = None
    request: Optional[Reference] = None
    status: Optional[Literal["in-progress", "not-done", "on-hold", "completed", "entered-in-error", "stopped", "unknown"]] = None
    status_reason: Optional[L[CodeableConcept]] = None
    subject: Optional[Reference] = None
    supporting_information: Optional[L[Reference]] = None

