# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class MedicationIngredient(BackboneElement):
    is_active: Optional[bool] = None
    item_codeable_concept: Optional[CodeableConcept] = None
    item_reference: Optional[Reference] = None
    strength: Optional[Ratio] = None

class MedicationBatch(BackboneElement):
    expiration_date: Optional[str] = None
    lot_number: Optional[str] = None


class Medication(DomainResource):
    amount: Optional[Ratio] = None
    batch: Optional[MedicationBatch] = None
    code: Optional[CodeableConcept] = None
    form: Optional[CodeableConcept] = None
    identifier: Optional[L[Identifier]] = None
    ingredient: Optional[L[MedicationIngredient]] = None
    manufacturer: Optional[Reference] = None
    status: Optional[Literal["active", "inactive", "entered-in-error"]] = None

