# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class OperationOutcomeIssue(BackboneElement):
    code: Optional[Literal["invalid", "security", "processing", "transient", "informational"]] = None
    details: Optional[CodeableConcept] = None
    diagnostics: Optional[str] = None
    expression: Optional[L[str]] = None
    location: Optional[L[str]] = None
    severity: Optional[Literal["fatal", "error", "warning", "information"]] = None


class OperationOutcome(DomainResource):
    issue: Optional[L[OperationOutcomeIssue]] = None

