# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .resource import Resource


class ParametersParameter(BackboneElement):
    name: Optional[str] = None
    part: Optional[L[ParametersParameter]] = None
    resource: Optional[Resource] = None
    value_address: Optional[Address] = None
    value_age: Optional[Age] = None
    value_annotation: Optional[Annotation] = None
    value_attachment: Optional[Attachment] = None
    value_base64binary: Optional[str] = None
    value_boolean: Optional[bool] = None
    value_canonical: Optional[str] = None
    value_code: Optional[str] = None
    value_codeable_concept: Optional[CodeableConcept] = None
    value_coding: Optional[Coding] = None
    value_contact_detail: Optional[ContactDetail] = None
    value_contact_point: Optional[ContactPoint] = None
    value_contributor: Optional[Contributor] = None
    value_count: Optional[Count] = None
    value_data_requirement: Optional[DataRequirement] = None
    value_date: Optional[str] = None
    value_date_time: Optional[str] = None
    value_decimal: Optional[float] = None
    value_distance: Optional[Distance] = None
    value_dosage: Optional[Dosage] = None
    value_duration: Optional[Duration] = None
    value_expression: Optional[Expression] = None
    value_human_name: Optional[HumanName] = None
    value_id: Optional[str] = None
    value_identifier: Optional[Identifier] = None
    value_instant: Optional[str] = None
    value_integer: Optional[int] = None
    value_markdown: Optional[str] = None
    value_meta: Optional[Meta] = None
    value_money: Optional[Money] = None
    value_oid: Optional[str] = None
    value_parameter_definition: Optional[ParameterDefinition] = None
    value_period: Optional[Period] = None
    value_positive_int: Optional[PositiveInt] = None
    value_quantity: Optional[Quantity] = None
    value_range: Optional[Range] = None
    value_ratio: Optional[Ratio] = None
    value_reference: Optional[Reference] = None
    value_related_artifact: Optional[RelatedArtifact] = None
    value_sampled_data: Optional[SampledData] = None
    value_signature: Optional[Signature] = None
    value_string: Optional[str] = None
    value_time: Optional[str] = None
    value_timing: Optional[Timing] = None
    value_trigger_definition: Optional[TriggerDefinition] = None
    value_unsigned_int: Optional[int] = None
    value_uri: Optional[str] = None
    value_url: Optional[str] = None
    value_usage_context: Optional[UsageContext] = None
    value_uuid: Optional[str] = None


class Parameters(Resource):
    parameter: Optional[L[ParametersParameter]] = None

