# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class ProvenanceAgent(BackboneElement):
    on_behalf_of: Optional[Reference] = None
    role: Optional[L[CodeableConcept]] = None
    type: Optional[CodeableConcept] = None
    who: Optional[Reference] = None

class ProvenanceEntity(BackboneElement):
    agent: Optional[L[ProvenanceAgent]] = None
    role: Optional[Literal["derivation"]] = None
    what: Optional[Reference] = None


class Provenance(DomainResource):
    activity: Optional[CodeableConcept] = None
    agent: Optional[L[ProvenanceAgent]] = None
    entity: Optional[L[ProvenanceEntity]] = None
    location: Optional[Reference] = None
    occurred_date_time: Optional[str] = None
    occurred_period: Optional[Period] = None
    policy: Optional[L[str]] = None
    reason: Optional[L[CodeableConcept]] = None
    recorded: Optional[str] = None
    signature: Optional[L[Signature]] = None
    target: Optional[L[Reference]] = None

