# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class ResearchStudyArm(BackboneElement):
    description: Optional[str] = None
    name: Optional[str] = None
    type: Optional[CodeableConcept] = None

class ResearchStudyObjective(BackboneElement):
    name: Optional[str] = None
    type: Optional[CodeableConcept] = None


class ResearchStudy(DomainResource):
    arm: Optional[L[ResearchStudyArm]] = None
    category: Optional[L[CodeableConcept]] = None
    condition: Optional[L[CodeableConcept]] = None
    contact: Optional[L[ContactDetail]] = None
    description: Optional[str] = None
    enrollment: Optional[L[Reference]] = None
    focus: Optional[L[CodeableConcept]] = None
    identifier: Optional[L[Identifier]] = None
    keyword: Optional[L[CodeableConcept]] = None
    location: Optional[L[CodeableConcept]] = None
    note: Optional[L[Annotation]] = None
    objective: Optional[L[ResearchStudyObjective]] = None
    part_of: Optional[L[Reference]] = None
    period: Optional[Period] = None
    phase: Optional[CodeableConcept] = None
    primary_purpose_type: Optional[CodeableConcept] = None
    principal_investigator: Optional[Reference] = None
    protocol: Optional[L[Reference]] = None
    reason_stopped: Optional[CodeableConcept] = None
    related_artifact: Optional[L[RelatedArtifact]] = None
    site: Optional[L[Reference]] = None
    sponsor: Optional[Reference] = None
    status: Optional[Literal["active", "administratively-completed", "approved", "closed-to-accrual", "closed-to-accrual-and-intervention", "completed", "disapproved", "in-review", "temporarily-closed-to-accrual", "temporarily-closed-to-accrual-and-intervention", "withdrawn"]] = None
    title: Optional[str] = None

