# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class StructureMapGroupInput(BackboneElement):
    documentation: Optional[str] = None
    mode: Optional[Literal["source", "target"]] = None
    name: Optional[str] = None
    type: Optional[str] = None

class StructureMapGroupRuleSource(BackboneElement):
    check: Optional[str] = None
    condition: Optional[str] = None
    context: Optional[str] = None
    default_value_address: Optional[Address] = None
    default_value_age: Optional[Age] = None
    default_value_annotation: Optional[Annotation] = None
    default_value_attachment: Optional[Attachment] = None
    default_value_base64binary: Optional[str] = None
    default_value_boolean: Optional[bool] = None
    default_value_canonical: Optional[str] = None
    default_value_code: Optional[str] = None
    default_value_codeable_concept: Optional[CodeableConcept] = None
    default_value_coding: Optional[Coding] = None
    default_value_contact_detail: Optional[ContactDetail] = None
    default_value_contact_point: Optional[ContactPoint] = None
    default_value_contributor: Optional[Contributor] = None
    default_value_count: Optional[Count] = None
    default_value_data_requirement: Optional[DataRequirement] = None
    default_value_date: Optional[str] = None
    default_value_date_time: Optional[str] = None
    default_value_decimal: Optional[float] = None
    default_value_distance: Optional[Distance] = None
    default_value_dosage: Optional[Dosage] = None
    default_value_duration: Optional[Duration] = None
    default_value_expression: Optional[Expression] = None
    default_value_human_name: Optional[HumanName] = None
    default_value_id: Optional[str] = None
    default_value_identifier: Optional[Identifier] = None
    default_value_instant: Optional[str] = None
    default_value_integer: Optional[int] = None
    default_value_markdown: Optional[str] = None
    default_value_meta: Optional[Meta] = None
    default_value_money: Optional[Money] = None
    default_value_oid: Optional[str] = None
    default_value_parameter_definition: Optional[ParameterDefinition] = None
    default_value_period: Optional[Period] = None
    default_value_positive_int: Optional[PositiveInt] = None
    default_value_quantity: Optional[Quantity] = None
    default_value_range: Optional[Range] = None
    default_value_ratio: Optional[Ratio] = None
    default_value_reference: Optional[Reference] = None
    default_value_related_artifact: Optional[RelatedArtifact] = None
    default_value_sampled_data: Optional[SampledData] = None
    default_value_signature: Optional[Signature] = None
    default_value_string: Optional[str] = None
    default_value_time: Optional[str] = None
    default_value_timing: Optional[Timing] = None
    default_value_trigger_definition: Optional[TriggerDefinition] = None
    default_value_unsigned_int: Optional[int] = None
    default_value_uri: Optional[str] = None
    default_value_url: Optional[str] = None
    default_value_usage_context: Optional[UsageContext] = None
    default_value_uuid: Optional[str] = None
    element: Optional[str] = None
    list_mode: Optional[Literal["first", "not_first", "last", "not_last", "only_one"]] = None
    log_message: Optional[str] = None
    max: Optional[str] = None
    min: Optional[int] = None
    type: Optional[str] = None
    variable: Optional[str] = None

class StructureMapGroupRuleTargetParameter(BackboneElement):
    value_boolean: Optional[bool] = None
    value_decimal: Optional[float] = None
    value_id: Optional[str] = None
    value_integer: Optional[int] = None
    value_string: Optional[str] = None

class StructureMapGroupRuleTarget(BackboneElement):
    context: Optional[str] = None
    context_type: Optional[Literal["type", "variable"]] = None
    element: Optional[str] = None
    list_mode: Optional[L[Literal["first", "share", "last", "collate"]]] = None
    list_rule_id: Optional[str] = None
    parameter: Optional[L[StructureMapGroupRuleTargetParameter]] = None
    transform: Optional[Literal["create", "copy", "truncate", "escape", "cast", "append", "translate", "reference", "dateOp", "uuid", "pointer", "evaluate", "cc", "c", "qty", "id", "cp"]] = None
    variable: Optional[str] = None

class StructureMapGroupRuleDependent(BackboneElement):
    name: Optional[str] = None
    variable: Optional[L[str]] = None

class StructureMapGroupRule(BackboneElement):
    dependent: Optional[L[StructureMapGroupRuleDependent]] = None
    documentation: Optional[str] = None
    name: Optional[str] = None
    rule: Optional[L[StructureMapGroupRule]] = None
    source: Optional[L[StructureMapGroupRuleSource]] = None
    target: Optional[L[StructureMapGroupRuleTarget]] = None

class StructureMapGroup(BackboneElement):
    documentation: Optional[str] = None
    extends: Optional[str] = None
    input: Optional[L[StructureMapGroupInput]] = None
    name: Optional[str] = None
    rule: Optional[L[StructureMapGroupRule]] = None
    type_mode: Optional[Literal["none", "types", "type-and-types"]] = None

class StructureMapStructure(BackboneElement):
    alias: Optional[str] = None
    documentation: Optional[str] = None
    mode: Optional[Literal["source", "queried", "target", "produced"]] = None
    url: Optional[str] = None


class StructureMap(DomainResource):
    contact: Optional[L[ContactDetail]] = None
    copyright: Optional[str] = None
    date: Optional[str] = None
    description: Optional[str] = None
    experimental: Optional[bool] = None
    group: Optional[L[StructureMapGroup]] = None
    identifier: Optional[L[Identifier]] = None
    import_: Optional[L[str]] = None
    jurisdiction: Optional[L[CodeableConcept]] = None
    name: Optional[str] = None
    publisher: Optional[str] = None
    purpose: Optional[str] = None
    status: Optional[Literal["draft", "active", "retired", "unknown"]] = None
    structure: Optional[L[StructureMapStructure]] = None
    title: Optional[str] = None
    url: Optional[str] = None
    use_context: Optional[L[UsageContext]] = None
    version: Optional[str] = None

