# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class SubstanceSpecificationProperty(BackboneElement):
    amount_quantity: Optional[Quantity] = None
    amount_string: Optional[str] = None
    category: Optional[CodeableConcept] = None
    code: Optional[CodeableConcept] = None
    defining_substance_codeable_concept: Optional[CodeableConcept] = None
    defining_substance_reference: Optional[Reference] = None
    parameters: Optional[str] = None

class SubstanceSpecificationNameOfficial(BackboneElement):
    authority: Optional[CodeableConcept] = None
    date: Optional[str] = None
    status: Optional[CodeableConcept] = None

class SubstanceSpecificationName(BackboneElement):
    domain: Optional[L[CodeableConcept]] = None
    jurisdiction: Optional[L[CodeableConcept]] = None
    language: Optional[L[CodeableConcept]] = None
    name: Optional[str] = None
    official: Optional[L[SubstanceSpecificationNameOfficial]] = None
    preferred: Optional[bool] = None
    source: Optional[L[Reference]] = None
    status: Optional[CodeableConcept] = None
    synonym: Optional[L[SubstanceSpecificationName]] = None
    translation: Optional[L[SubstanceSpecificationName]] = None
    type: Optional[CodeableConcept] = None

class SubstanceSpecificationRelationship(BackboneElement):
    amount_quantity: Optional[Quantity] = None
    amount_range: Optional[Range] = None
    amount_ratio: Optional[Ratio] = None
    amount_ratio_low_limit: Optional[Ratio] = None
    amount_string: Optional[str] = None
    amount_type: Optional[CodeableConcept] = None
    is_defining: Optional[bool] = None
    relationship: Optional[CodeableConcept] = None
    source: Optional[L[Reference]] = None
    substance_codeable_concept: Optional[CodeableConcept] = None
    substance_reference: Optional[Reference] = None

class SubstanceSpecificationMoiety(BackboneElement):
    amount_quantity: Optional[Quantity] = None
    amount_string: Optional[str] = None
    identifier: Optional[Identifier] = None
    molecular_formula: Optional[str] = None
    name: Optional[str] = None
    optical_activity: Optional[CodeableConcept] = None
    role: Optional[CodeableConcept] = None
    stereochemistry: Optional[CodeableConcept] = None

class SubstanceSpecificationStructureIsotopeMolecularWeight(BackboneElement):
    amount: Optional[Quantity] = None
    method: Optional[CodeableConcept] = None
    type: Optional[CodeableConcept] = None

class SubstanceSpecificationStructureIsotope(BackboneElement):
    half_life: Optional[Quantity] = None
    identifier: Optional[Identifier] = None
    molecular_weight: Optional[SubstanceSpecificationStructureIsotopeMolecularWeight] = None
    name: Optional[CodeableConcept] = None
    substitution: Optional[CodeableConcept] = None

class SubstanceSpecificationStructureRepresentation(BackboneElement):
    attachment: Optional[Attachment] = None
    representation: Optional[str] = None
    type: Optional[CodeableConcept] = None

class SubstanceSpecificationStructure(BackboneElement):
    isotope: Optional[L[SubstanceSpecificationStructureIsotope]] = None
    molecular_formula: Optional[str] = None
    molecular_formula_by_moiety: Optional[str] = None
    molecular_weight: Optional[SubstanceSpecificationStructureIsotopeMolecularWeight] = None
    optical_activity: Optional[CodeableConcept] = None
    representation: Optional[L[SubstanceSpecificationStructureRepresentation]] = None
    source: Optional[L[Reference]] = None
    stereochemistry: Optional[CodeableConcept] = None

class SubstanceSpecificationCode(BackboneElement):
    code: Optional[CodeableConcept] = None
    comment: Optional[str] = None
    source: Optional[L[Reference]] = None
    status: Optional[CodeableConcept] = None
    status_date: Optional[str] = None


class SubstanceSpecification(DomainResource):
    code: Optional[L[SubstanceSpecificationCode]] = None
    comment: Optional[str] = None
    description: Optional[str] = None
    domain: Optional[CodeableConcept] = None
    identifier: Optional[Identifier] = None
    moiety: Optional[L[SubstanceSpecificationMoiety]] = None
    molecular_weight: Optional[L[SubstanceSpecificationStructureIsotopeMolecularWeight]] = None
    name: Optional[L[SubstanceSpecificationName]] = None
    nucleic_acid: Optional[Reference] = None
    polymer: Optional[Reference] = None
    property: Optional[L[SubstanceSpecificationProperty]] = None
    protein: Optional[Reference] = None
    reference_information: Optional[Reference] = None
    relationship: Optional[L[SubstanceSpecificationRelationship]] = None
    source: Optional[L[Reference]] = None
    source_material: Optional[Reference] = None
    status: Optional[CodeableConcept] = None
    structure: Optional[SubstanceSpecificationStructure] = None
    type: Optional[CodeableConcept] = None

