# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class SubstanceProteinSubunit(BackboneElement):
    c_terminal_modification: Optional[str] = None
    c_terminal_modification_id: Optional[Identifier] = None
    length: Optional[int] = None
    n_terminal_modification: Optional[str] = None
    n_terminal_modification_id: Optional[Identifier] = None
    sequence: Optional[str] = None
    sequence_attachment: Optional[Attachment] = None
    subunit: Optional[int] = None


class SubstanceProtein(DomainResource):
    disulfide_linkage: Optional[L[str]] = None
    number_of_subunits: Optional[int] = None
    sequence_type: Optional[CodeableConcept] = None
    subunit: Optional[L[SubstanceProteinSubunit]] = None

