# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import *
from typing import Optional, List as L, Literal

from .base import *
from .domain_resource import DomainResource


class SupplyRequestParameter(BackboneElement):
    code: Optional[CodeableConcept] = None
    value_boolean: Optional[bool] = None
    value_codeable_concept: Optional[CodeableConcept] = None
    value_quantity: Optional[Quantity] = None
    value_range: Optional[Range] = None


class SupplyRequest(DomainResource):
    authored_on: Optional[str] = None
    category: Optional[CodeableConcept] = None
    deliver_from: Optional[Reference] = None
    deliver_to: Optional[Reference] = None
    identifier: Optional[L[Identifier]] = None
    item_codeable_concept: Optional[CodeableConcept] = None
    item_reference: Optional[Reference] = None
    occurrence_date_time: Optional[str] = None
    occurrence_period: Optional[Period] = None
    occurrence_timing: Optional[Timing] = None
    parameter: Optional[L[SupplyRequestParameter]] = None
    priority: Optional[Literal["routine", "urgent", "asap", "stat"]] = None
    quantity: Optional[Quantity] = None
    reason_code: Optional[L[CodeableConcept]] = None
    reason_reference: Optional[L[Reference]] = None
    requester: Optional[Reference] = None
    status: Optional[Literal["draft", "active", "suspended", "cancelled", "completed", "entered-in-error", "unknown"]] = None
    supplier: Optional[L[Reference]] = None

